// Copyright 2025 Google LLC
// SPDX-License-Identifier: Apache-2.0

import Foundation

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.
// Ports `_internal_types.ts`.

/// Private struct that represents a reference image that is sent to API.
public struct ReferenceImageAPIInternal: Codable, Sendable {
    /// The reference image for the editing operation.
    public var referenceImage: Image?
    /// The id of the reference image.
    public var referenceId: Double?
    /// The type of the reference image. Only set by the SDK.
    public var referenceType: String?
    /// Configuration for the mask reference image.
    public var maskImageConfig: MaskReferenceConfig?
    /// Configuration for the control reference image.
    public var controlImageConfig: ControlReferenceConfig?
    /// Configuration for the style reference image.
    public var styleImageConfig: StyleReferenceConfig?
    /// Configuration for the subject reference image.
    public var subjectImageConfig: SubjectReferenceConfig?

    public init(
        referenceImage: Image? = nil,
        referenceId: Double? = nil,
        referenceType: String? = nil,
        maskImageConfig: MaskReferenceConfig? = nil,
        controlImageConfig: ControlReferenceConfig? = nil,
        styleImageConfig: StyleReferenceConfig? = nil,
        subjectImageConfig: SubjectReferenceConfig? = nil
    ) {
        self.referenceImage = referenceImage
        self.referenceId = referenceId
        self.referenceType = referenceType
        self.maskImageConfig = maskImageConfig
        self.controlImageConfig = controlImageConfig
        self.styleImageConfig = styleImageConfig
        self.subjectImageConfig = subjectImageConfig
    }
}

/// Parameters for the request to edit an image.
public struct EditImageParametersInternal: Codable, Sendable {
    /// The model to use.
    public var model: String
    /// A text description of the edit to apply to the image.
    public var prompt: String
    /// The reference images for editing.
    public var referenceImages: [ReferenceImageAPIInternal]
    /// Configuration for editing.
    public var config: EditImageConfig?

    public init(
        model: String,
        prompt: String,
        referenceImages: [ReferenceImageAPIInternal],
        config: EditImageConfig? = nil
    ) {
        self.model = model
        self.prompt = prompt
        self.referenceImages = referenceImages
        self.config = config
    }
}

/// Internal API config for UpscaleImage.
///
/// These fields require default values sent to the API which are not intended
/// to be modifiable or exposed to users in the SDK method.
public struct UpscaleImageAPIConfigInternal: Codable, Sendable {
    /// Used to override HTTP request options.
    public var httpOptions: HttpOptions?
    /// Abort signal which can be used to cancel the request.
    public var abortSignal: AbortSignal?
    /// Cloud Storage URI used to store the generated images.
    public var outputGcsUri: String?
    /// Filter level for safety filtering.
    public var safetyFilterLevel: SafetyFilterLevel?
    /// Allows generation of people by the model.
    public var personGeneration: PersonGeneration?
    /// Whether to include a reason for filtered-out images in the response.
    public var includeRaiReason: Bool?
    /// The image format that the output should be saved as.
    public var outputMimeType: String?
    /// The level of compression. Only applicable if the `output_mime_type` is `image/jpeg`.
    public var outputCompressionQuality: Double?
    /// Whether to add an image enhancing step before upscaling.
    public var enhanceInputImage: Bool?
    /// Image preservation factor.
    public var imagePreservationFactor: Double?
    /// User specified labels to track billing usage.
    public var labels: [String: String]?
    public var numberOfImages: Int?
    public var mode: String?

    public init(
        httpOptions: HttpOptions? = nil,
        abortSignal: AbortSignal? = nil,
        outputGcsUri: String? = nil,
        safetyFilterLevel: SafetyFilterLevel? = nil,
        personGeneration: PersonGeneration? = nil,
        includeRaiReason: Bool? = nil,
        outputMimeType: String? = nil,
        outputCompressionQuality: Double? = nil,
        enhanceInputImage: Bool? = nil,
        imagePreservationFactor: Double? = nil,
        labels: [String: String]? = nil,
        numberOfImages: Int? = nil,
        mode: String? = nil
    ) {
        self.httpOptions = httpOptions
        self.abortSignal = abortSignal
        self.outputGcsUri = outputGcsUri
        self.safetyFilterLevel = safetyFilterLevel
        self.personGeneration = personGeneration
        self.includeRaiReason = includeRaiReason
        self.outputMimeType = outputMimeType
        self.outputCompressionQuality = outputCompressionQuality
        self.enhanceInputImage = enhanceInputImage
        self.imagePreservationFactor = imagePreservationFactor
        self.labels = labels
        self.numberOfImages = numberOfImages
        self.mode = mode
    }
}

/// API parameters for UpscaleImage.
public struct UpscaleImageAPIParametersInternal: Codable, Sendable {
    /// The model to use.
    public var model: String
    /// The input image to upscale.
    public var image: Image
    /// The factor to upscale the image (x2 or x4).
    public var upscaleFactor: String
    /// Configuration for upscaling.
    public var config: UpscaleImageAPIConfigInternal?

    public init(
        model: String,
        image: Image,
        upscaleFactor: String,
        config: UpscaleImageAPIConfigInternal? = nil
    ) {
        self.model = model
        self.image = image
        self.upscaleFactor = upscaleFactor
        self.config = config
    }
}
