// Copyright 2025 Google LLC
// SPDX-License-Identifier: Apache-2.0

import Foundation

/// Server message indicating that setup is complete.
public struct LiveServerSetupComplete: Codable, Sendable {
    /// The session id of the live session.
    public var sessionId: String?

    public init(sessionId: String? = nil) {
        self.sessionId = sessionId
    }
}

/// Audio transcription in Server Content.
public struct Transcription: Codable, Sendable {
    /// Optional. Transcription text.
    public var text: String?
    /// Optional. The bool indicates the end of the transcription.
    public var finished: Bool?

    public init(text: String? = nil, finished: Bool? = nil) {
        self.text = text
        self.finished = finished
    }
}

/// Incremental server update generated by the model in response to client messages.
public struct LiveServerContent: Codable, Sendable {
    /// The content that the model has generated as part of the current conversation with the user.
    public var modelTurn: Content?
    /// If true, indicates that the model is done generating.
    public var turnComplete: Bool?
    /// If true, indicates that a client message has interrupted current model generation.
    public var interrupted: Bool?
    /// Metadata returned to client when grounding is enabled.
    public var groundingMetadata: GroundingMetadata?
    /// If true, indicates that the model is done generating.
    public var generationComplete: Bool?
    /// Input transcription.
    public var inputTranscription: Transcription?
    /// Output transcription.
    public var outputTranscription: Transcription?
    /// Metadata related to url context retrieval tool.
    public var urlContextMetadata: UrlContextMetadata?
    /// Reason for the turn is complete.
    public var turnCompleteReason: TurnCompleteReason?
    /// If true, indicates that the model is not generating content because it is waiting for more input.
    public var waitingForInput: Bool?

    public init(
        modelTurn: Content? = nil,
        turnComplete: Bool? = nil,
        interrupted: Bool? = nil,
        groundingMetadata: GroundingMetadata? = nil,
        generationComplete: Bool? = nil,
        inputTranscription: Transcription? = nil,
        outputTranscription: Transcription? = nil,
        urlContextMetadata: UrlContextMetadata? = nil,
        turnCompleteReason: TurnCompleteReason? = nil,
        waitingForInput: Bool? = nil
    ) {
        self.modelTurn = modelTurn
        self.turnComplete = turnComplete
        self.interrupted = interrupted
        self.groundingMetadata = groundingMetadata
        self.generationComplete = generationComplete
        self.inputTranscription = inputTranscription
        self.outputTranscription = outputTranscription
        self.urlContextMetadata = urlContextMetadata
        self.turnCompleteReason = turnCompleteReason
        self.waitingForInput = waitingForInput
    }
}

/// Request for the client to execute the `function_calls` and return the responses with the matching `id`s.
public struct LiveServerToolCall: Codable, Sendable {
    /// The function call to be executed.
    public var functionCalls: [FunctionCall]?

    public init(functionCalls: [FunctionCall]? = nil) {
        self.functionCalls = functionCalls
    }
}

/// Notification for the client that previously issued tool calls should be cancelled.
public struct LiveServerToolCallCancellation: Codable, Sendable {
    /// The ids of the tool calls to be cancelled.
    public var ids: [String]?

    public init(ids: [String]? = nil) {
        self.ids = ids
    }
}

/// Usage metadata about response(s).
public struct UsageMetadata: Codable, Sendable {
    /// Number of tokens in the prompt.
    public var promptTokenCount: Double?
    /// Number of tokens in the cached part of the prompt.
    public var cachedContentTokenCount: Double?
    /// Total number of tokens across all the generated response candidates.
    public var responseTokenCount: Double?
    /// Number of tokens present in tool-use prompt(s).
    public var toolUsePromptTokenCount: Double?
    /// Number of tokens of thoughts for thinking models.
    public var thoughtsTokenCount: Double?
    /// Total token count for prompt, response candidates, and tool-use prompts.
    public var totalTokenCount: Double?
    /// List of modalities that were processed in the request input.
    public var promptTokensDetails: [ModalityTokenCount]?
    /// List of modalities that were processed in the cache input.
    public var cacheTokensDetails: [ModalityTokenCount]?
    /// List of modalities that were returned in the response.
    public var responseTokensDetails: [ModalityTokenCount]?
    /// List of modalities that were processed in the tool-use prompt.
    public var toolUsePromptTokensDetails: [ModalityTokenCount]?
    /// Traffic type.
    public var trafficType: TrafficType?

    public init(
        promptTokenCount: Double? = nil,
        cachedContentTokenCount: Double? = nil,
        responseTokenCount: Double? = nil,
        toolUsePromptTokenCount: Double? = nil,
        thoughtsTokenCount: Double? = nil,
        totalTokenCount: Double? = nil,
        promptTokensDetails: [ModalityTokenCount]? = nil,
        cacheTokensDetails: [ModalityTokenCount]? = nil,
        responseTokensDetails: [ModalityTokenCount]? = nil,
        toolUsePromptTokensDetails: [ModalityTokenCount]? = nil,
        trafficType: TrafficType? = nil
    ) {
        self.promptTokenCount = promptTokenCount
        self.cachedContentTokenCount = cachedContentTokenCount
        self.responseTokenCount = responseTokenCount
        self.toolUsePromptTokenCount = toolUsePromptTokenCount
        self.thoughtsTokenCount = thoughtsTokenCount
        self.totalTokenCount = totalTokenCount
        self.promptTokensDetails = promptTokensDetails
        self.cacheTokensDetails = cacheTokensDetails
        self.responseTokensDetails = responseTokensDetails
        self.toolUsePromptTokensDetails = toolUsePromptTokensDetails
        self.trafficType = trafficType
    }
}

/// Server will not be able to service client soon.
public struct LiveServerGoAway: Codable, Sendable {
    /// The remaining time before the connection will be terminated as ABORTED.
    public var timeLeft: String?

    public init(timeLeft: String? = nil) {
        self.timeLeft = timeLeft
    }
}

/// Update of the session resumption state.
public struct LiveServerSessionResumptionUpdate: Codable, Sendable {
    /// New handle that represents state that can be resumed.
    public var newHandle: String?
    /// True if session can be resumed at this point.
    public var resumable: Bool?
    /// Index of last message sent by client that is included in state represented by this token.
    public var lastConsumedClientMessageIndex: String?

    public init(
        newHandle: String? = nil,
        resumable: Bool? = nil,
        lastConsumedClientMessageIndex: String? = nil
    ) {
        self.newHandle = newHandle
        self.resumable = resumable
        self.lastConsumedClientMessageIndex = lastConsumedClientMessageIndex
    }
}

/// Voice activity detection signal.
public struct VoiceActivityDetectionSignal: Codable, Sendable {
    /// The type of the VAD signal.
    public var vadSignalType: VadSignalType?

    public init(vadSignalType: VadSignalType? = nil) {
        self.vadSignalType = vadSignalType
    }
}

/// Voice activity signal.
public struct VoiceActivity: Codable, Sendable {
    /// The type of the voice activity signal.
    public var voiceActivityType: VoiceActivityType?

    public init(voiceActivityType: VoiceActivityType? = nil) {
        self.voiceActivityType = voiceActivityType
    }
}

/// Response message for API call.
public final class LiveServerMessage: Codable, @unchecked Sendable {
    /// Sent in response to a `LiveClientSetup` message from the client.
    public var setupComplete: LiveServerSetupComplete?
    /// Content generated by the model in response to client messages.
    public var serverContent: LiveServerContent?
    /// Request for the client to execute the `function_calls`.
    public var toolCall: LiveServerToolCall?
    /// Notification for the client that a previously issued tool call should be cancelled.
    public var toolCallCancellation: LiveServerToolCallCancellation?
    /// Usage metadata about model response(s).
    public var usageMetadata: UsageMetadata?
    /// Server will disconnect soon.
    public var goAway: LiveServerGoAway?
    /// Update of the session resumption state.
    public var sessionResumptionUpdate: LiveServerSessionResumptionUpdate?
    /// Voice activity detection signal. Allowlisted only.
    public var voiceActivityDetectionSignal: VoiceActivityDetectionSignal?
    /// Voice activity signal.
    public var voiceActivity: VoiceActivity?

    public init(
        setupComplete: LiveServerSetupComplete? = nil,
        serverContent: LiveServerContent? = nil,
        toolCall: LiveServerToolCall? = nil,
        toolCallCancellation: LiveServerToolCallCancellation? = nil,
        usageMetadata: UsageMetadata? = nil,
        goAway: LiveServerGoAway? = nil,
        sessionResumptionUpdate: LiveServerSessionResumptionUpdate? = nil,
        voiceActivityDetectionSignal: VoiceActivityDetectionSignal? = nil,
        voiceActivity: VoiceActivity? = nil
    ) {
        self.setupComplete = setupComplete
        self.serverContent = serverContent
        self.toolCall = toolCall
        self.toolCallCancellation = toolCallCancellation
        self.usageMetadata = usageMetadata
        self.goAway = goAway
        self.sessionResumptionUpdate = sessionResumptionUpdate
        self.voiceActivityDetectionSignal = voiceActivityDetectionSignal
        self.voiceActivity = voiceActivity
    }

    /// Returns the concatenation of all text parts from the server content if present.
    public var text: String? {
        var result = ""
        var anyTextPartFound = false
        var nonTextParts: [String] = []
        for part in serverContent?.modelTurn?.parts ?? [] {
            if part.inlineData != nil { nonTextParts.append("inlineData") }
            if part.fileData != nil { nonTextParts.append("fileData") }
            if part.functionCall != nil { nonTextParts.append("functionCall") }
            if part.functionResponse != nil { nonTextParts.append("functionResponse") }
            if part.executableCode != nil { nonTextParts.append("executableCode") }
            if part.codeExecutionResult != nil { nonTextParts.append("codeExecutionResult") }
            if part.videoMetadata != nil { nonTextParts.append("videoMetadata") }
            if let textValue = part.text {
                if part.thought == true { continue }
                anyTextPartFound = true
                result += textValue
            }
        }
        if !nonTextParts.isEmpty {
            // swift-genai: parity with JS console.warn
            print("there are non-text parts \(nonTextParts) in the response, returning concatenation of all text parts.")
        }
        return anyTextPartFound ? result : nil
    }

    /// Returns the concatenation of all inline data parts from the server content if present.
    public var data: String? {
        var raw = Data()
        var nonDataParts: [String] = []
        for part in serverContent?.modelTurn?.parts ?? [] {
            if part.text != nil { nonDataParts.append("text") }
            if part.fileData != nil { nonDataParts.append("fileData") }
            if part.functionCall != nil { nonDataParts.append("functionCall") }
            if part.functionResponse != nil { nonDataParts.append("functionResponse") }
            if part.executableCode != nil { nonDataParts.append("executableCode") }
            if part.codeExecutionResult != nil { nonDataParts.append("codeExecutionResult") }
            if part.videoMetadata != nil { nonDataParts.append("videoMetadata") }
            if let inline = part.inlineData, let str = inline.data,
               let decoded = Data(base64Encoded: str) {
                raw.append(decoded)
            }
        }
        if !nonDataParts.isEmpty {
            print("there are non-data parts \(nonDataParts) in the response, returning concatenation of all data parts.")
        }
        return raw.isEmpty ? nil : raw.base64EncodedString()
    }
}

/// Parameters of the fromAPIResponse method of the Operation class.
public struct OperationFromAPIResponseParameters: @unchecked Sendable {
    /// The API client used to call the converters.
    public var apiClient: ApiClient
    /// The API response to be converted to an Operation.
    public var apiResponse: [String: JSONValue]
    /// Whether the API response is from Vertex AI.
    public var isVertexAI: Bool

    public init(apiClient: ApiClient, apiResponse: [String: JSONValue], isVertexAI: Bool) {
        self.apiClient = apiClient
        self.apiResponse = apiResponse
        self.isVertexAI = isVertexAI
    }
}

/// Config for thinking feature.
///
/// - Note: Deprecated in TS; aliased to `ThinkingConfig`.
public typealias GenerationConfigThinkingConfig = ThinkingConfig

/// Generates the parameters for the private registerFiles method.
public struct RegisterFilesParameters: Sendable {
    /// The authentication object.
    public var auth: JSONValue?
    /// The Google Cloud Storage URIs to register. Example: `gs://bucket/object`.
    public var uris: [String]
    /// Used to override the default configuration.
    public var config: RegisterFilesConfig?

    public init(auth: JSONValue? = nil, uris: [String], config: RegisterFilesConfig? = nil) {
        self.auth = auth
        self.uris = uris
        self.config = config
    }
}

/// Configures automatic detection of activity.
public struct AutomaticActivityDetection: Codable, Sendable {
    /// If enabled, detected voice and text input count as activity.
    public var disabled: Bool?
    /// Determines how likely speech is to be detected.
    public var startOfSpeechSensitivity: StartSensitivity?
    /// Determines how likely detected speech is ended.
    public var endOfSpeechSensitivity: EndSensitivity?
    /// The required duration of detected speech before start-of-speech is committed.
    public var prefixPaddingMs: Double?
    /// The required duration of detected non-speech before end-of-speech is committed.
    public var silenceDurationMs: Double?

    public init(
        disabled: Bool? = nil,
        startOfSpeechSensitivity: StartSensitivity? = nil,
        endOfSpeechSensitivity: EndSensitivity? = nil,
        prefixPaddingMs: Double? = nil,
        silenceDurationMs: Double? = nil
    ) {
        self.disabled = disabled
        self.startOfSpeechSensitivity = startOfSpeechSensitivity
        self.endOfSpeechSensitivity = endOfSpeechSensitivity
        self.prefixPaddingMs = prefixPaddingMs
        self.silenceDurationMs = silenceDurationMs
    }
}

/// Configures the realtime input behavior in BidiGenerateContent.
public struct RealtimeInputConfig: Codable, Sendable {
    /// If not set, automatic activity detection is enabled by default.
    public var automaticActivityDetection: AutomaticActivityDetection?
    /// Defines what effect activity has.
    public var activityHandling: ActivityHandling?
    /// Defines which input is included in the user's turn.
    public var turnCoverage: TurnCoverage?

    public init(
        automaticActivityDetection: AutomaticActivityDetection? = nil,
        activityHandling: ActivityHandling? = nil,
        turnCoverage: TurnCoverage? = nil
    ) {
        self.automaticActivityDetection = automaticActivityDetection
        self.activityHandling = activityHandling
        self.turnCoverage = turnCoverage
    }
}

/// Configuration of session resumption mechanism.
public struct SessionResumptionConfig: Codable, Sendable {
    /// Session resumption handle of previous session (session to restore).
    public var handle: String?
    /// If set the server will send `last_consumed_client_message_index` in the update messages.
    public var transparent: Bool?

    public init(handle: String? = nil, transparent: Bool? = nil) {
        self.handle = handle
        self.transparent = transparent
    }
}

/// Context window will be truncated by keeping only suffix of it.
public struct SlidingWindow: Codable, Sendable {
    /// Session reduction target -- how many tokens we should keep.
    public var targetTokens: String?

    public init(targetTokens: String? = nil) {
        self.targetTokens = targetTokens
    }
}

/// Enables context window compression.
public struct ContextWindowCompressionConfig: Codable, Sendable {
    /// Number of tokens (before running turn) that triggers context window compression mechanism.
    public var triggerTokens: String?
    /// Sliding window compression mechanism.
    public var slidingWindow: SlidingWindow?

    public init(triggerTokens: String? = nil, slidingWindow: SlidingWindow? = nil) {
        self.triggerTokens = triggerTokens
        self.slidingWindow = slidingWindow
    }
}

/// The audio transcription configuration in Setup.
public struct AudioTranscriptionConfig: Codable, Sendable {
    /// The language codes of the audio. BCP-47 language code.
    public var languageCodes: [String]?

    public init(languageCodes: [String]? = nil) {
        self.languageCodes = languageCodes
    }
}

/// Config for proactivity features.
public struct ProactivityConfig: Codable, Sendable {
    /// If enabled, the model can reject responding to the last prompt.
    public var proactiveAudio: Bool?

    public init(proactiveAudio: Bool? = nil) {
        self.proactiveAudio = proactiveAudio
    }
}

/// Configures the customized avatar to be used in the session.
public struct CustomizedAvatar: Codable, Sendable {
    /// The mime type of the reference image, e.g., "image/jpeg".
    public var imageMimeType: String?
    /// The data of the reference image, encoded as base64 string.
    public var imageData: String?

    public init(imageMimeType: String? = nil, imageData: String? = nil) {
        self.imageMimeType = imageMimeType
        self.imageData = imageData
    }
}

/// Configures the avatar to be used in the session.
public struct AvatarConfig: Codable, Sendable {
    /// Pre-built avatar id.
    public var avatarName: String?
    /// Customized avatar appearance with a reference image.
    public var customizedAvatar: CustomizedAvatar?
    /// The bitrate of compressed audio.
    public var audioBitrateBps: Double?
    /// The bitrate of compressed video output.
    public var videoBitrateBps: Double?

    public init(
        avatarName: String? = nil,
        customizedAvatar: CustomizedAvatar? = nil,
        audioBitrateBps: Double? = nil,
        videoBitrateBps: Double? = nil
    ) {
        self.avatarName = avatarName
        self.customizedAvatar = customizedAvatar
        self.audioBitrateBps = audioBitrateBps
        self.videoBitrateBps = videoBitrateBps
    }
}

/// Message contains configuration that will apply for the duration of the streaming session.
public struct LiveClientSetup: Sendable {
    /// The fully qualified name of the publisher model or tuned model endpoint to use.
    public var model: String?
    /// The generation configuration for the session.
    public var generationConfig: GenerationConfig?
    /// The user provided system instructions for the model.
    public var systemInstruction: ContentUnion?
    /// A list of `Tools` the model may use to generate the next response.
    public var tools: ToolListUnion?
    /// Configures the realtime input behavior in BidiGenerateContent.
    public var realtimeInputConfig: RealtimeInputConfig?
    /// Configures session resumption mechanism.
    public var sessionResumption: SessionResumptionConfig?
    /// Configures context window compression mechanism.
    public var contextWindowCompression: ContextWindowCompressionConfig?
    /// The transcription of the input aligns with the input audio language.
    public var inputAudioTranscription: AudioTranscriptionConfig?
    /// The transcription of the output aligns with the language code specified for the output audio.
    public var outputAudioTranscription: AudioTranscriptionConfig?
    /// Configures the proactivity of the model.
    public var proactivity: ProactivityConfig?
    /// Configures the explicit VAD signal.
    public var explicitVadSignal: Bool?
    /// Configures the avatar model behavior.
    public var avatarConfig: AvatarConfig?
    /// Safety settings in the request to block unsafe content in the response.
    public var safetySettings: [SafetySetting]?

    public init(
        model: String? = nil,
        generationConfig: GenerationConfig? = nil,
        systemInstruction: ContentUnion? = nil,
        tools: ToolListUnion? = nil,
        realtimeInputConfig: RealtimeInputConfig? = nil,
        sessionResumption: SessionResumptionConfig? = nil,
        contextWindowCompression: ContextWindowCompressionConfig? = nil,
        inputAudioTranscription: AudioTranscriptionConfig? = nil,
        outputAudioTranscription: AudioTranscriptionConfig? = nil,
        proactivity: ProactivityConfig? = nil,
        explicitVadSignal: Bool? = nil,
        avatarConfig: AvatarConfig? = nil,
        safetySettings: [SafetySetting]? = nil
    ) {
        self.model = model
        self.generationConfig = generationConfig
        self.systemInstruction = systemInstruction
        self.tools = tools
        self.realtimeInputConfig = realtimeInputConfig
        self.sessionResumption = sessionResumption
        self.contextWindowCompression = contextWindowCompression
        self.inputAudioTranscription = inputAudioTranscription
        self.outputAudioTranscription = outputAudioTranscription
        self.proactivity = proactivity
        self.explicitVadSignal = explicitVadSignal
        self.avatarConfig = avatarConfig
        self.safetySettings = safetySettings
    }
}

/// Incremental update of the current conversation delivered from the client.
public struct LiveClientContent: Codable, Sendable {
    /// The content appended to the current conversation with the model.
    public var turns: [Content]?
    /// If true, indicates that the server content generation should start.
    public var turnComplete: Bool?

    public init(turns: [Content]? = nil, turnComplete: Bool? = nil) {
        self.turns = turns
        self.turnComplete = turnComplete
    }
}

/// Marks the start of user activity.
public struct ActivityStart: Codable, Sendable {
    public init() {}
}

/// Marks the end of user activity.
public struct ActivityEnd: Codable, Sendable {
    public init() {}
}

/// User input that is sent in real time.
public struct LiveClientRealtimeInput: Codable, Sendable {
    /// Inlined bytes data for media input.
    public var mediaChunks: [Blob]?
    /// The realtime audio input stream.
    public var audio: Blob?
    /// Indicates that the audio stream has ended.
    public var audioStreamEnd: Bool?
    /// The realtime video input stream.
    public var video: Blob?
    /// The realtime text input stream.
    public var text: String?
    /// Marks the start of user activity.
    public var activityStart: ActivityStart?
    /// Marks the end of user activity.
    public var activityEnd: ActivityEnd?

    public init(
        mediaChunks: [Blob]? = nil,
        audio: Blob? = nil,
        audioStreamEnd: Bool? = nil,
        video: Blob? = nil,
        text: String? = nil,
        activityStart: ActivityStart? = nil,
        activityEnd: ActivityEnd? = nil
    ) {
        self.mediaChunks = mediaChunks
        self.audio = audio
        self.audioStreamEnd = audioStreamEnd
        self.video = video
        self.text = text
        self.activityStart = activityStart
        self.activityEnd = activityEnd
    }
}

/// Client generated response to a `ToolCall` received from the server.
public final class LiveClientToolResponse: Codable, @unchecked Sendable {
    /// The response to the function calls.
    public var functionResponses: [FunctionResponse]?

    public init(functionResponses: [FunctionResponse]? = nil) {
        self.functionResponses = functionResponses
    }
}

/// Messages sent by the client in the API call.
public struct LiveClientMessage: Sendable {
    /// Message to be sent by the system when connecting to the API.
    public var setup: LiveClientSetup?
    /// Incremental update of the current conversation delivered from the client.
    public var clientContent: LiveClientContent?
    /// User input that is sent in real time.
    public var realtimeInput: LiveClientRealtimeInput?
    /// Response to a `ToolCallMessage` received from the server.
    public var toolResponse: LiveClientToolResponse?

    public init(
        setup: LiveClientSetup? = nil,
        clientContent: LiveClientContent? = nil,
        realtimeInput: LiveClientRealtimeInput? = nil,
        toolResponse: LiveClientToolResponse? = nil
    ) {
        self.setup = setup
        self.clientContent = clientContent
        self.realtimeInput = realtimeInput
        self.toolResponse = toolResponse
    }
}

/// Config for stream translation.
public struct StreamTranslationConfig: Codable, Sendable {
    /// If true, the model will generate audio when the target language is spoken.
    public var echoTargetLanguage: Bool?
    /// The target language for translation. BCP-47 language codes (e.g. "en", "es", "fr").
    public var targetLanguageCode: String?

    public init(echoTargetLanguage: Bool? = nil, targetLanguageCode: String? = nil) {
        self.echoTargetLanguage = echoTargetLanguage
        self.targetLanguageCode = targetLanguageCode
    }
}

/// Session config for the API connection.
public struct LiveConnectConfig: Codable, Sendable {
    /// Used to override HTTP request options.
    public var httpOptions: HttpOptions?
    /// Abort signal which can be used to cancel the request.
    public var abortSignal: AbortSignal?
    /// The generation configuration for the session.
    public var generationConfig: GenerationConfig?
    /// The requested modalities of the response.
    public var responseModalities: [Modality]?
    /// Value that controls the degree of randomness in token selection.
    public var temperature: Double?
    /// Tokens are selected from the most to least probable until the sum of their probabilities equals this value.
    public var topP: Double?
    /// For each token selection step, the top_k tokens with the highest probabilities are sampled.
    public var topK: Double?
    /// Maximum number of tokens that can be generated in the response.
    public var maxOutputTokens: Double?
    /// If specified, the media resolution specified will be used.
    public var mediaResolution: MediaResolution?
    /// When seed is fixed to a specific number, the model makes a best effort to provide the same response.
    public var seed: Double?
    /// The speech generation configuration.
    public var speechConfig: SpeechConfig?
    /// Config for thinking features.
    public var thinkingConfig: ThinkingConfig?
    /// If enabled, the model will detect emotions and adapt its responses accordingly.
    public var enableAffectiveDialog: Bool?
    /// The user provided system instructions for the model.
    public var systemInstruction: ContentUnion?
    /// A list of `Tools` the model may use to generate the next response.
    public var tools: ToolListUnion?
    /// Configures session resumption mechanism.
    public var sessionResumption: SessionResumptionConfig?
    /// The transcription of the input aligns with the input audio language.
    public var inputAudioTranscription: AudioTranscriptionConfig?
    /// The transcription of the output aligns with the language code specified for the output audio.
    public var outputAudioTranscription: AudioTranscriptionConfig?
    /// Configures the realtime input behavior in BidiGenerateContent.
    public var realtimeInputConfig: RealtimeInputConfig?
    /// Configures context window compression mechanism.
    public var contextWindowCompression: ContextWindowCompressionConfig?
    /// Configures the proactivity of the model.
    public var proactivity: ProactivityConfig?
    /// Configures the explicit VAD signal.
    public var explicitVadSignal: Bool?
    /// Configures the avatar model behavior.
    public var avatarConfig: AvatarConfig?
    /// Safety settings in the request to block unsafe content in the response.
    public var safetySettings: [SafetySetting]?
    /// Config for stream translation.
    public var streamTranslationConfig: StreamTranslationConfig?

    public init(
        httpOptions: HttpOptions? = nil,
        abortSignal: AbortSignal? = nil,
        generationConfig: GenerationConfig? = nil,
        responseModalities: [Modality]? = nil,
        temperature: Double? = nil,
        topP: Double? = nil,
        topK: Double? = nil,
        maxOutputTokens: Double? = nil,
        mediaResolution: MediaResolution? = nil,
        seed: Double? = nil,
        speechConfig: SpeechConfig? = nil,
        thinkingConfig: ThinkingConfig? = nil,
        enableAffectiveDialog: Bool? = nil,
        systemInstruction: ContentUnion? = nil,
        tools: ToolListUnion? = nil,
        sessionResumption: SessionResumptionConfig? = nil,
        inputAudioTranscription: AudioTranscriptionConfig? = nil,
        outputAudioTranscription: AudioTranscriptionConfig? = nil,
        realtimeInputConfig: RealtimeInputConfig? = nil,
        contextWindowCompression: ContextWindowCompressionConfig? = nil,
        proactivity: ProactivityConfig? = nil,
        explicitVadSignal: Bool? = nil,
        avatarConfig: AvatarConfig? = nil,
        safetySettings: [SafetySetting]? = nil,
        streamTranslationConfig: StreamTranslationConfig? = nil
    ) {
        self.httpOptions = httpOptions
        self.abortSignal = abortSignal
        self.generationConfig = generationConfig
        self.responseModalities = responseModalities
        self.temperature = temperature
        self.topP = topP
        self.topK = topK
        self.maxOutputTokens = maxOutputTokens
        self.mediaResolution = mediaResolution
        self.seed = seed
        self.speechConfig = speechConfig
        self.thinkingConfig = thinkingConfig
        self.enableAffectiveDialog = enableAffectiveDialog
        self.systemInstruction = systemInstruction
        self.tools = tools
        self.sessionResumption = sessionResumption
        self.inputAudioTranscription = inputAudioTranscription
        self.outputAudioTranscription = outputAudioTranscription
        self.realtimeInputConfig = realtimeInputConfig
        self.contextWindowCompression = contextWindowCompression
        self.proactivity = proactivity
        self.explicitVadSignal = explicitVadSignal
        self.avatarConfig = avatarConfig
        self.safetySettings = safetySettings
        self.streamTranslationConfig = streamTranslationConfig
    }
}

/// Callbacks for the realtime API.
///
/// - Note: Not `Codable` — function-typed members can't be encoded/decoded.
public struct LiveCallbacks: Sendable {
    /// Called when a message is received from the server.
    public var onMessage: @Sendable (LiveServerMessage) -> Void
    /// Called when an error occurs.
    public var onError: (@Sendable (Error) -> Void)?
    /// Called when the websocket connection is opened.
    public var onOpen: (@Sendable () -> Void)?
    /// Called when the websocket connection is closed.
    public var onClose: (@Sendable (Error?) -> Void)?

    public init(
        onMessage: @escaping @Sendable (LiveServerMessage) -> Void,
        onError: (@Sendable (Error) -> Void)? = nil,
        onOpen: (@Sendable () -> Void)? = nil,
        onClose: (@Sendable (Error?) -> Void)? = nil
    ) {
        self.onMessage = onMessage
        self.onError = onError
        self.onOpen = onOpen
        self.onClose = onClose
    }
}

/// Parameters for connecting to the live API.
public struct LiveConnectParameters: Sendable {
    /// ID of the model to use.
    public var model: String
    /// Callbacks.
    public var callbacks: LiveCallbacks
    /// Optional configuration parameters for the request.
    public var config: LiveConnectConfig?

    public init(model: String, callbacks: LiveCallbacks, config: LiveConnectConfig? = nil) {
        self.model = model
        self.callbacks = callbacks
        self.config = config
    }
}

/// Parameters for initializing a new chat session.
public struct CreateChatParameters: Sendable {
    /// The name of the model to use for the chat session.
    public var model: String
    /// Config for the entire chat session.
    public var config: GenerateContentConfig?
    /// The initial conversation history for the chat session.
    public var history: [Content]?

    public init(model: String, config: GenerateContentConfig? = nil, history: [Content]? = nil) {
        self.model = model
        self.config = config
        self.history = history
    }
}

/// Parameters for sending a message within a chat session.
public struct SendMessageParameters: Sendable {
    /// The message to send to the model.
    public var message: PartListUnion
    /// Config for this specific request.
    public var config: GenerateContentConfig?

    public init(message: PartListUnion, config: GenerateContentConfig? = nil) {
        self.message = message
        self.config = config
    }
}

/// Parameters for sending client content to the live API.
public struct LiveSendClientContentParameters: Sendable {
    /// Client content to send to the session.
    public var turns: ContentListUnion?
    /// If true, indicates that the server content generation should start.
    public var turnComplete: Bool?

    public init(turns: ContentListUnion? = nil, turnComplete: Bool? = nil) {
        self.turns = turns
        self.turnComplete = turnComplete
    }
}

/// Parameters for sending realtime input to the live API.
public struct LiveSendRealtimeInputParameters: Sendable {
    /// Realtime input to send to the session.
    public var media: BlobImageUnion?
    /// The realtime audio input stream.
    public var audio: Blob?
    /// Indicates that the audio stream has ended.
    public var audioStreamEnd: Bool?
    /// The realtime video input stream.
    public var video: BlobImageUnion?
    /// The realtime text input stream.
    public var text: String?
    /// Marks the start of user activity.
    public var activityStart: ActivityStart?
    /// Marks the end of user activity.
    public var activityEnd: ActivityEnd?

    public init(
        media: BlobImageUnion? = nil,
        audio: Blob? = nil,
        audioStreamEnd: Bool? = nil,
        video: BlobImageUnion? = nil,
        text: String? = nil,
        activityStart: ActivityStart? = nil,
        activityEnd: ActivityEnd? = nil
    ) {
        self.media = media
        self.audio = audio
        self.audioStreamEnd = audioStreamEnd
        self.video = video
        self.text = text
        self.activityStart = activityStart
        self.activityEnd = activityEnd
    }
}

/// Parameters for sending tool responses to the live API.
public final class LiveSendToolResponseParameters: @unchecked Sendable {
    /// Tool responses to send to the session.
    public var functionResponses: [FunctionResponse]

    public init(functionResponses: [FunctionResponse] = []) {
        self.functionResponses = functionResponses
    }
}
