// Copyright 2025 Google LLC
// SPDX-License-Identifier: Apache-2.0

import Foundation

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.
//
// NOTE: The following converters are also defined in `_caches_converters.ts`
// but are duplicated in other TS converter files. To avoid Swift name
// collisions inside a single module, this file relies on the canonical
// definitions in `LiveConverters.swift`:
//   authConfigToMldev, blobToMldev, contentToMldev, contentToVertex,
//   fileDataToMldev, functionCallToMldev, googleMapsToMldev,
//   googleSearchToMldev, partToMldev, partToVertex, toolToMldev,
//   toolToVertex.
// And on `ModelsConvertersPart1.swift` / `ModelsConvertersPart2.swift` for:
//   functionCallingConfigToMldev, toolConfigToMldev, toolConfigToVertex.

public func createCachedContentConfigToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromTtl = getValueByPath(.object(fromObject), ["ttl"])
    if case .null = fromTtl {} else {
        try setValueByPath(&parentObject, ["ttl"], fromTtl)
    }

    let fromExpireTime = getValueByPath(.object(fromObject), ["expireTime"])
    if case .null = fromExpireTime {} else {
        try setValueByPath(&parentObject, ["expireTime"], fromExpireTime)
    }

    let fromDisplayName = getValueByPath(.object(fromObject), ["displayName"])
    if case .null = fromDisplayName {} else {
        try setValueByPath(&parentObject, ["displayName"], fromDisplayName)
    }

    let fromContents = getValueByPath(.object(fromObject), ["contents"])
    if case .null = fromContents {} else {
        var transformed: JSONValue = fromContents
        if case .array(let arr) = fromContents {
            var mapped: [JSONValue] = []
            for item in arr {
                if case .object(let itemObj) = item {
                    var dummy: [String: JSONValue] = [:]
                    let result = try contentToMldev(apiClient: apiClient, fromObject: itemObj, parentObject: &dummy)
                    mapped.append(.object(result))
                } else {
                    mapped.append(item)
                }
            }
            transformed = .array(mapped)
        }
        try setValueByPath(&parentObject, ["contents"], transformed)
    }

    let fromSystemInstruction = getValueByPath(.object(fromObject), ["systemInstruction"])
    if case .object(let siObj) = fromSystemInstruction {
        var dummy: [String: JSONValue] = [:]
        let converted = try contentToMldev(apiClient: apiClient, fromObject: siObj, parentObject: &dummy)
        try setValueByPath(&parentObject, ["systemInstruction"], .object(converted))
    }

    let fromTools = getValueByPath(.object(fromObject), ["tools"])
    if case .null = fromTools {} else {
        var transformed: JSONValue = fromTools
        if case .array(let arr) = fromTools {
            var mapped: [JSONValue] = []
            for item in arr {
                if case .object(let itemObj) = item {
                    var dummy: [String: JSONValue] = [:]
                    let result = try toolToMldev(apiClient: apiClient, fromObject: itemObj, parentObject: &dummy)
                    mapped.append(.object(result))
                } else {
                    mapped.append(item)
                }
            }
            transformed = .array(mapped)
        }
        try setValueByPath(&parentObject, ["tools"], transformed)
    }

    let fromToolConfig = getValueByPath(.object(fromObject), ["toolConfig"])
    if case .object(let tcObj) = fromToolConfig {
        var dummy: [String: JSONValue] = [:]
        let converted = try toolConfigToMldev(apiClient: apiClient, fromObject: tcObj, parentObject: &dummy)
        try setValueByPath(&parentObject, ["toolConfig"], .object(converted))
    }

    if case .null = getValueByPath(.object(fromObject), ["kmsKeyName"]) {} else {
        throw GenAIError.runtime(
            "kmsKeyName parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    return toObject
}

public func createCachedContentConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromTtl = getValueByPath(.object(fromObject), ["ttl"])
    if case .null = fromTtl {} else {
        try setValueByPath(&parentObject, ["ttl"], fromTtl)
    }

    let fromExpireTime = getValueByPath(.object(fromObject), ["expireTime"])
    if case .null = fromExpireTime {} else {
        try setValueByPath(&parentObject, ["expireTime"], fromExpireTime)
    }

    let fromDisplayName = getValueByPath(.object(fromObject), ["displayName"])
    if case .null = fromDisplayName {} else {
        try setValueByPath(&parentObject, ["displayName"], fromDisplayName)
    }

    let fromContents = getValueByPath(.object(fromObject), ["contents"])
    if case .null = fromContents {} else {
        var transformed: JSONValue = fromContents
        if case .array(let arr) = fromContents {
            var mapped: [JSONValue] = []
            for item in arr {
                if case .object(let itemObj) = item {
                    var dummy: [String: JSONValue] = [:]
                    let result = try contentToVertex(apiClient: apiClient, fromObject: itemObj, parentObject: &dummy)
                    mapped.append(.object(result))
                } else {
                    mapped.append(item)
                }
            }
            transformed = .array(mapped)
        }
        try setValueByPath(&parentObject, ["contents"], transformed)
    }

    let fromSystemInstruction = getValueByPath(.object(fromObject), ["systemInstruction"])
    if case .object(let siObj) = fromSystemInstruction {
        var dummy: [String: JSONValue] = [:]
        let converted = try contentToVertex(apiClient: apiClient, fromObject: siObj, parentObject: &dummy)
        try setValueByPath(&parentObject, ["systemInstruction"], .object(converted))
    }

    let fromTools = getValueByPath(.object(fromObject), ["tools"])
    if case .null = fromTools {} else {
        var transformed: JSONValue = fromTools
        if case .array(let arr) = fromTools {
            var mapped: [JSONValue] = []
            for item in arr {
                if case .object(let itemObj) = item {
                    var dummy: [String: JSONValue] = [:]
                    let result = try toolToVertex(apiClient: apiClient, fromObject: itemObj, parentObject: &dummy)
                    mapped.append(.object(result))
                } else {
                    mapped.append(item)
                }
            }
            transformed = .array(mapped)
        }
        try setValueByPath(&parentObject, ["tools"], transformed)
    }

    let fromToolConfig = getValueByPath(.object(fromObject), ["toolConfig"])
    if case .object(let tcObj) = fromToolConfig {
        var dummy: [String: JSONValue] = [:]
        let converted = try toolConfigToVertex(apiClient: apiClient, fromObject: tcObj, parentObject: &dummy)
        try setValueByPath(&parentObject, ["toolConfig"], .object(converted))
    }

    let fromKmsKeyName = getValueByPath(.object(fromObject), ["kmsKeyName"])
    if case .null = fromKmsKeyName {} else {
        try setValueByPath(&parentObject, ["encryption_spec", "kmsKeyName"], fromKmsKeyName)
    }

    return toObject
}

public func createCachedContentParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        let modelStr = try tCachesModel(apiClient: apiClient, model: fromModel)
        try setValueByPath(&toObject, ["model"], .string(modelStr))
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try createCachedContentConfigToMldev(apiClient: apiClient, fromObject: configObj, parentObject: &toObject)
    }

    return toObject
}

public func createCachedContentParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        let modelStr = try tCachesModel(apiClient: apiClient, model: fromModel)
        try setValueByPath(&toObject, ["model"], .string(modelStr))
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try createCachedContentConfigToVertex(apiClient: apiClient, fromObject: configObj, parentObject: &toObject)
    }

    return toObject
}

public func deleteCachedContentParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        let nameStr = try tCachedContentName(apiClient: apiClient, name: fromName)
        try setValueByPath(&toObject, ["_url", "name"], .string(nameStr))
    }

    return toObject
}

public func deleteCachedContentParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        let nameStr = try tCachedContentName(apiClient: apiClient, name: fromName)
        try setValueByPath(&toObject, ["_url", "name"], .string(nameStr))
    }

    return toObject
}

public func deleteCachedContentResponseFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    return toObject
}

public func deleteCachedContentResponseFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    return toObject
}

public func getCachedContentParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        let nameStr = try tCachedContentName(apiClient: apiClient, name: fromName)
        try setValueByPath(&toObject, ["_url", "name"], .string(nameStr))
    }

    return toObject
}

public func getCachedContentParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        let nameStr = try tCachedContentName(apiClient: apiClient, name: fromName)
        try setValueByPath(&toObject, ["_url", "name"], .string(nameStr))
    }

    return toObject
}

public func listCachedContentsConfigToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromPageSize = getValueByPath(.object(fromObject), ["pageSize"])
    if case .null = fromPageSize {} else {
        try setValueByPath(&parentObject, ["_query", "pageSize"], fromPageSize)
    }

    let fromPageToken = getValueByPath(.object(fromObject), ["pageToken"])
    if case .null = fromPageToken {} else {
        try setValueByPath(&parentObject, ["_query", "pageToken"], fromPageToken)
    }

    return toObject
}

public func listCachedContentsConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromPageSize = getValueByPath(.object(fromObject), ["pageSize"])
    if case .null = fromPageSize {} else {
        try setValueByPath(&parentObject, ["_query", "pageSize"], fromPageSize)
    }

    let fromPageToken = getValueByPath(.object(fromObject), ["pageToken"])
    if case .null = fromPageToken {} else {
        try setValueByPath(&parentObject, ["_query", "pageToken"], fromPageToken)
    }

    return toObject
}

public func listCachedContentsParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try listCachedContentsConfigToMldev(apiClient: apiClient, fromObject: configObj, parentObject: &toObject)
    }

    return toObject
}

public func listCachedContentsParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try listCachedContentsConfigToVertex(apiClient: apiClient, fromObject: configObj, parentObject: &toObject)
    }

    return toObject
}

public func listCachedContentsResponseFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    let fromNextPageToken = getValueByPath(.object(fromObject), ["nextPageToken"])
    if case .null = fromNextPageToken {} else {
        try setValueByPath(&toObject, ["nextPageToken"], fromNextPageToken)
    }

    let fromCachedContents = getValueByPath(.object(fromObject), ["cachedContents"])
    if case .null = fromCachedContents {} else {
        try setValueByPath(&toObject, ["cachedContents"], fromCachedContents)
    }

    return toObject
}

public func listCachedContentsResponseFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    let fromNextPageToken = getValueByPath(.object(fromObject), ["nextPageToken"])
    if case .null = fromNextPageToken {} else {
        try setValueByPath(&toObject, ["nextPageToken"], fromNextPageToken)
    }

    let fromCachedContents = getValueByPath(.object(fromObject), ["cachedContents"])
    if case .null = fromCachedContents {} else {
        try setValueByPath(&toObject, ["cachedContents"], fromCachedContents)
    }

    return toObject
}

public func updateCachedContentConfigToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromTtl = getValueByPath(.object(fromObject), ["ttl"])
    if case .null = fromTtl {} else {
        try setValueByPath(&parentObject, ["ttl"], fromTtl)
    }

    let fromExpireTime = getValueByPath(.object(fromObject), ["expireTime"])
    if case .null = fromExpireTime {} else {
        try setValueByPath(&parentObject, ["expireTime"], fromExpireTime)
    }

    return toObject
}

public func updateCachedContentConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromTtl = getValueByPath(.object(fromObject), ["ttl"])
    if case .null = fromTtl {} else {
        try setValueByPath(&parentObject, ["ttl"], fromTtl)
    }

    let fromExpireTime = getValueByPath(.object(fromObject), ["expireTime"])
    if case .null = fromExpireTime {} else {
        try setValueByPath(&parentObject, ["expireTime"], fromExpireTime)
    }

    return toObject
}

public func updateCachedContentParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        let nameStr = try tCachedContentName(apiClient: apiClient, name: fromName)
        try setValueByPath(&toObject, ["_url", "name"], .string(nameStr))
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try updateCachedContentConfigToMldev(apiClient: apiClient, fromObject: configObj, parentObject: &toObject)
    }

    return toObject
}

public func updateCachedContentParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        let nameStr = try tCachedContentName(apiClient: apiClient, name: fromName)
        try setValueByPath(&toObject, ["_url", "name"], .string(nameStr))
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try updateCachedContentConfigToVertex(apiClient: apiClient, fromObject: configObj, parentObject: &toObject)
    }

    return toObject
}
