// Copyright 2025 Google LLC
// SPDX-License-Identifier: Apache-2.0

import Foundation

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.
// Ported from js-genai/src/converters/_models_converters.ts lines 3020-5851.

// MARK: - generateVideosParametersToMldev

public func generateVideosParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        try setValueByPath(&toObject, ["_url", "model"], .string(try tModel(apiClient: apiClient, model: fromModel)))
    }

    let fromPrompt = getValueByPath(.object(fromObject), ["prompt"])
    if case .null = fromPrompt {} else {
        try setValueByPath(&toObject, ["instances[0]", "prompt"], fromPrompt)
    }

    let fromImage = getValueByPath(.object(fromObject), ["image"])
    if case .object(let imageObj) = fromImage {
        var _dummyParent2: [String: JSONValue] = [:]
        let converted = try imageToMldev(apiClient: apiClient, fromObject: imageObj, parentObject: &_dummyParent2)
        try setValueByPath(&toObject, ["instances[0]", "image"], .object(converted))
    }

    let fromVideo = getValueByPath(.object(fromObject), ["video"])
    if case .object(let videoObj) = fromVideo {
        var _dummyParent3: [String: JSONValue] = [:]
        let converted = try videoToMldev(apiClient: apiClient, fromObject: videoObj, parentObject: &_dummyParent3)
        try setValueByPath(&toObject, ["instances[0]", "video"], .object(converted))
    }

    let fromSource = getValueByPath(.object(fromObject), ["source"])
    if case .object(let sourceObj) = fromSource {
        _ = try generateVideosSourceToMldev(apiClient: apiClient, fromObject: sourceObj, parentObject: &toObject)
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try generateVideosConfigToMldev(apiClient: apiClient, fromObject: configObj, parentObject: &toObject)
    }

    return toObject
}

// MARK: - generateVideosParametersToVertex

public func generateVideosParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        try setValueByPath(&toObject, ["_url", "model"], .string(try tModel(apiClient: apiClient, model: fromModel)))
    }

    let fromPrompt = getValueByPath(.object(fromObject), ["prompt"])
    if case .null = fromPrompt {} else {
        try setValueByPath(&toObject, ["instances[0]", "prompt"], fromPrompt)
    }

    let fromImage = getValueByPath(.object(fromObject), ["image"])
    if case .object(let imageObj) = fromImage {
        var _dummyParent4: [String: JSONValue] = [:]
        let converted = try imageToVertex(apiClient: apiClient, fromObject: imageObj, parentObject: &_dummyParent4)
        try setValueByPath(&toObject, ["instances[0]", "image"], .object(converted))
    }

    let fromVideo = getValueByPath(.object(fromObject), ["video"])
    if case .object(let videoObj) = fromVideo {
        var _dummyParent5: [String: JSONValue] = [:]
        let converted = try videoToVertex(apiClient: apiClient, fromObject: videoObj, parentObject: &_dummyParent5)
        try setValueByPath(&toObject, ["instances[0]", "video"], .object(converted))
    }

    let fromSource = getValueByPath(.object(fromObject), ["source"])
    if case .object(let sourceObj) = fromSource {
        _ = try generateVideosSourceToVertex(apiClient: apiClient, fromObject: sourceObj, parentObject: &toObject)
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try generateVideosConfigToVertex(apiClient: apiClient, fromObject: configObj, parentObject: &toObject)
    }

    return toObject
}

// MARK: - generateVideosSourceToMldev

public func generateVideosSourceToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromPrompt = getValueByPath(.object(fromObject), ["prompt"])
    if case .null = fromPrompt {} else {
        try setValueByPath(&parentObject, ["instances[0]", "prompt"], fromPrompt)
    }

    let fromImage = getValueByPath(.object(fromObject), ["image"])
    if case .object(let imageObj) = fromImage {
        var _dummyParent8: [String: JSONValue] = [:]
        let converted = try imageToMldev(apiClient: apiClient, fromObject: imageObj, parentObject: &_dummyParent8)
        try setValueByPath(&parentObject, ["instances[0]", "image"], .object(converted))
    }

    let fromVideo = getValueByPath(.object(fromObject), ["video"])
    if case .object(let videoObj) = fromVideo {
        var _dummyParent9: [String: JSONValue] = [:]
        let converted = try videoToMldev(apiClient: apiClient, fromObject: videoObj, parentObject: &_dummyParent9)
        try setValueByPath(&parentObject, ["instances[0]", "video"], .object(converted))
    }

    return toObject
}

// MARK: - generateVideosSourceToVertex

public func generateVideosSourceToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromPrompt = getValueByPath(.object(fromObject), ["prompt"])
    if case .null = fromPrompt {} else {
        try setValueByPath(&parentObject, ["instances[0]", "prompt"], fromPrompt)
    }

    let fromImage = getValueByPath(.object(fromObject), ["image"])
    if case .object(let imageObj) = fromImage {
        var _dummyParent10: [String: JSONValue] = [:]
        let converted = try imageToVertex(apiClient: apiClient, fromObject: imageObj, parentObject: &_dummyParent10)
        try setValueByPath(&parentObject, ["instances[0]", "image"], .object(converted))
    }

    let fromVideo = getValueByPath(.object(fromObject), ["video"])
    if case .object(let videoObj) = fromVideo {
        var _dummyParent11: [String: JSONValue] = [:]
        let converted = try videoToVertex(apiClient: apiClient, fromObject: videoObj, parentObject: &_dummyParent11)
        try setValueByPath(&parentObject, ["instances[0]", "video"], .object(converted))
    }

    return toObject
}

// MARK: - generatedImageFromMldev

public func generatedImageFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromImage = getValueByPath(.object(fromObject), ["_self"])
    if case .null = fromImage {} else if case .object(let imgObj) = fromImage {
        var _dummyParent12: [String: JSONValue] = [:]
        let converted = try imageFromMldev(apiClient: apiClient, fromObject: imgObj, parentObject: &_dummyParent12)
        try setValueByPath(&toObject, ["image"], .object(converted))
    }

    let fromRaiFilteredReason = getValueByPath(.object(fromObject), ["raiFilteredReason"])
    if case .null = fromRaiFilteredReason {} else {
        try setValueByPath(&toObject, ["raiFilteredReason"], fromRaiFilteredReason)
    }

    let fromSafetyAttributes = getValueByPath(.object(fromObject), ["_self"])
    if case .null = fromSafetyAttributes {} else if case .object(let saObj) = fromSafetyAttributes {
        var _dummyParent13: [String: JSONValue] = [:]
        let converted = try safetyAttributesFromMldev(apiClient: apiClient, fromObject: saObj, parentObject: &_dummyParent13)
        try setValueByPath(&toObject, ["safetyAttributes"], .object(converted))
    }

    return toObject
}

// MARK: - generatedImageFromVertex

public func generatedImageFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromImage = getValueByPath(.object(fromObject), ["_self"])
    if case .null = fromImage {} else if case .object(let imgObj) = fromImage {
        var _dummyParent14: [String: JSONValue] = [:]
        let converted = try imageFromVertex(apiClient: apiClient, fromObject: imgObj, parentObject: &_dummyParent14)
        try setValueByPath(&toObject, ["image"], .object(converted))
    }

    let fromRaiFilteredReason = getValueByPath(.object(fromObject), ["raiFilteredReason"])
    if case .null = fromRaiFilteredReason {} else {
        try setValueByPath(&toObject, ["raiFilteredReason"], fromRaiFilteredReason)
    }

    let fromSafetyAttributes = getValueByPath(.object(fromObject), ["_self"])
    if case .null = fromSafetyAttributes {} else if case .object(let saObj) = fromSafetyAttributes {
        var _dummyParent15: [String: JSONValue] = [:]
        let converted = try safetyAttributesFromVertex(apiClient: apiClient, fromObject: saObj, parentObject: &_dummyParent15)
        try setValueByPath(&toObject, ["safetyAttributes"], .object(converted))
    }

    let fromEnhancedPrompt = getValueByPath(.object(fromObject), ["prompt"])
    if case .null = fromEnhancedPrompt {} else {
        try setValueByPath(&toObject, ["enhancedPrompt"], fromEnhancedPrompt)
    }

    return toObject
}

// MARK: - generatedImageMaskFromVertex

public func generatedImageMaskFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromMask = getValueByPath(.object(fromObject), ["_self"])
    if case .null = fromMask {} else if case .object(let maskObj) = fromMask {
        var _dummyParent16: [String: JSONValue] = [:]
        let converted = try imageFromVertex(apiClient: apiClient, fromObject: maskObj, parentObject: &_dummyParent16)
        try setValueByPath(&toObject, ["mask"], .object(converted))
    }

    let fromLabels = getValueByPath(.object(fromObject), ["labels"])
    if case .null = fromLabels {} else {
        try setValueByPath(&toObject, ["labels"], fromLabels)
    }

    return toObject
}

// MARK: - generationConfigToVertex

public func generationConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromModelSelectionConfig = getValueByPath(.object(fromObject), ["modelSelectionConfig"])
    if case .null = fromModelSelectionConfig {} else {
        try setValueByPath(&toObject, ["modelConfig"], fromModelSelectionConfig)
    }

    let fromResponseJsonSchema = getValueByPath(.object(fromObject), ["responseJsonSchema"])
    if case .null = fromResponseJsonSchema {} else {
        try setValueByPath(&toObject, ["responseJsonSchema"], fromResponseJsonSchema)
    }

    let fromAudioTimestamp = getValueByPath(.object(fromObject), ["audioTimestamp"])
    if case .null = fromAudioTimestamp {} else {
        try setValueByPath(&toObject, ["audioTimestamp"], fromAudioTimestamp)
    }

    let fromCandidateCount = getValueByPath(.object(fromObject), ["candidateCount"])
    if case .null = fromCandidateCount {} else {
        try setValueByPath(&toObject, ["candidateCount"], fromCandidateCount)
    }

    let fromEnableAffectiveDialog = getValueByPath(.object(fromObject), ["enableAffectiveDialog"])
    if case .null = fromEnableAffectiveDialog {} else {
        try setValueByPath(&toObject, ["enableAffectiveDialog"], fromEnableAffectiveDialog)
    }

    let fromFrequencyPenalty = getValueByPath(.object(fromObject), ["frequencyPenalty"])
    if case .null = fromFrequencyPenalty {} else {
        try setValueByPath(&toObject, ["frequencyPenalty"], fromFrequencyPenalty)
    }

    let fromLogprobs = getValueByPath(.object(fromObject), ["logprobs"])
    if case .null = fromLogprobs {} else {
        try setValueByPath(&toObject, ["logprobs"], fromLogprobs)
    }

    let fromMaxOutputTokens = getValueByPath(.object(fromObject), ["maxOutputTokens"])
    if case .null = fromMaxOutputTokens {} else {
        try setValueByPath(&toObject, ["maxOutputTokens"], fromMaxOutputTokens)
    }

    let fromMediaResolution = getValueByPath(.object(fromObject), ["mediaResolution"])
    if case .null = fromMediaResolution {} else {
        try setValueByPath(&toObject, ["mediaResolution"], fromMediaResolution)
    }

    let fromPresencePenalty = getValueByPath(.object(fromObject), ["presencePenalty"])
    if case .null = fromPresencePenalty {} else {
        try setValueByPath(&toObject, ["presencePenalty"], fromPresencePenalty)
    }

    let fromResponseLogprobs = getValueByPath(.object(fromObject), ["responseLogprobs"])
    if case .null = fromResponseLogprobs {} else {
        try setValueByPath(&toObject, ["responseLogprobs"], fromResponseLogprobs)
    }

    let fromResponseMimeType = getValueByPath(.object(fromObject), ["responseMimeType"])
    if case .null = fromResponseMimeType {} else {
        try setValueByPath(&toObject, ["responseMimeType"], fromResponseMimeType)
    }

    let fromResponseModalities = getValueByPath(.object(fromObject), ["responseModalities"])
    if case .null = fromResponseModalities {} else {
        try setValueByPath(&toObject, ["responseModalities"], fromResponseModalities)
    }

    let fromResponseSchema = getValueByPath(.object(fromObject), ["responseSchema"])
    if case .null = fromResponseSchema {} else {
        try setValueByPath(&toObject, ["responseSchema"], fromResponseSchema)
    }

    let fromRoutingConfig = getValueByPath(.object(fromObject), ["routingConfig"])
    if case .null = fromRoutingConfig {} else {
        try setValueByPath(&toObject, ["routingConfig"], fromRoutingConfig)
    }

    let fromSeed = getValueByPath(.object(fromObject), ["seed"])
    if case .null = fromSeed {} else {
        try setValueByPath(&toObject, ["seed"], fromSeed)
    }

    let fromSpeechConfig = getValueByPath(.object(fromObject), ["speechConfig"])
    if case .null = fromSpeechConfig {} else {
        try setValueByPath(&toObject, ["speechConfig"], fromSpeechConfig)
    }

    let fromStopSequences = getValueByPath(.object(fromObject), ["stopSequences"])
    if case .null = fromStopSequences {} else {
        try setValueByPath(&toObject, ["stopSequences"], fromStopSequences)
    }

    let fromTemperature = getValueByPath(.object(fromObject), ["temperature"])
    if case .null = fromTemperature {} else {
        try setValueByPath(&toObject, ["temperature"], fromTemperature)
    }

    let fromThinkingConfig = getValueByPath(.object(fromObject), ["thinkingConfig"])
    if case .null = fromThinkingConfig {} else {
        try setValueByPath(&toObject, ["thinkingConfig"], fromThinkingConfig)
    }

    let fromTopK = getValueByPath(.object(fromObject), ["topK"])
    if case .null = fromTopK {} else {
        try setValueByPath(&toObject, ["topK"], fromTopK)
    }

    let fromTopP = getValueByPath(.object(fromObject), ["topP"])
    if case .null = fromTopP {} else {
        try setValueByPath(&toObject, ["topP"], fromTopP)
    }

    let enableEnhancedCivicAnswers = getValueByPath(.object(fromObject), ["enableEnhancedCivicAnswers"])
    if case .null = enableEnhancedCivicAnswers {} else {
        throw GenAIError.runtime("enableEnhancedCivicAnswers parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode.")
    }

    return toObject
}

// MARK: - getModelParametersToMldev

public func getModelParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        try setValueByPath(&toObject, ["_url", "name"], .string(try tModel(apiClient: apiClient, model: fromModel)))
    }

    return toObject
}

// MARK: - getModelParametersToVertex

public func getModelParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        try setValueByPath(&toObject, ["_url", "name"], .string(try tModel(apiClient: apiClient, model: fromModel)))
    }

    return toObject
}

// MARK: - googleMapsToMldev

public func googleMapsToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromAuthConfig = getValueByPath(.object(fromObject), ["authConfig"])
    if case .object(let acObj) = fromAuthConfig {
        var _dummyParent19: [String: JSONValue] = [:]
        let converted = try authConfigToMldev(apiClient: apiClient, fromObject: acObj, parentObject: &_dummyParent19)
        try setValueByPath(&toObject, ["authConfig"], .object(converted))
    }

    let fromEnableWidget = getValueByPath(.object(fromObject), ["enableWidget"])
    if case .null = fromEnableWidget {} else {
        try setValueByPath(&toObject, ["enableWidget"], fromEnableWidget)
    }

    return toObject
}

// MARK: - googleSearchToMldev

public func googleSearchToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromSearchTypes = getValueByPath(.object(fromObject), ["searchTypes"])
    if case .null = fromSearchTypes {} else {
        try setValueByPath(&toObject, ["searchTypes"], fromSearchTypes)
    }

    let blockingConfidence = getValueByPath(.object(fromObject), ["blockingConfidence"])
    if case .null = blockingConfidence {} else {
        throw GenAIError.runtime("blockingConfidence parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let excludeDomains = getValueByPath(.object(fromObject), ["excludeDomains"])
    if case .null = excludeDomains {} else {
        throw GenAIError.runtime("excludeDomains parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let fromTimeRangeFilter = getValueByPath(.object(fromObject), ["timeRangeFilter"])
    if case .null = fromTimeRangeFilter {} else {
        try setValueByPath(&toObject, ["timeRangeFilter"], fromTimeRangeFilter)
    }

    return toObject
}

// MARK: - imageConfigToMldev

public func imageConfigToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromAspectRatio = getValueByPath(.object(fromObject), ["aspectRatio"])
    if case .null = fromAspectRatio {} else {
        try setValueByPath(&toObject, ["aspectRatio"], fromAspectRatio)
    }

    let fromImageSize = getValueByPath(.object(fromObject), ["imageSize"])
    if case .null = fromImageSize {} else {
        try setValueByPath(&toObject, ["imageSize"], fromImageSize)
    }

    let personGeneration = getValueByPath(.object(fromObject), ["personGeneration"])
    if case .null = personGeneration {} else {
        throw GenAIError.runtime("personGeneration parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let prominentPeople = getValueByPath(.object(fromObject), ["prominentPeople"])
    if case .null = prominentPeople {} else {
        throw GenAIError.runtime("prominentPeople parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let outputMimeType = getValueByPath(.object(fromObject), ["outputMimeType"])
    if case .null = outputMimeType {} else {
        throw GenAIError.runtime("outputMimeType parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let outputCompressionQuality = getValueByPath(.object(fromObject), ["outputCompressionQuality"])
    if case .null = outputCompressionQuality {} else {
        throw GenAIError.runtime("outputCompressionQuality parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let imageOutputOptions = getValueByPath(.object(fromObject), ["imageOutputOptions"])
    if case .null = imageOutputOptions {} else {
        throw GenAIError.runtime("imageOutputOptions parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    return toObject
}

// MARK: - imageConfigToVertex

public func imageConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromAspectRatio = getValueByPath(.object(fromObject), ["aspectRatio"])
    if case .null = fromAspectRatio {} else {
        try setValueByPath(&toObject, ["aspectRatio"], fromAspectRatio)
    }

    let fromImageSize = getValueByPath(.object(fromObject), ["imageSize"])
    if case .null = fromImageSize {} else {
        try setValueByPath(&toObject, ["imageSize"], fromImageSize)
    }

    let fromPersonGeneration = getValueByPath(.object(fromObject), ["personGeneration"])
    if case .null = fromPersonGeneration {} else {
        try setValueByPath(&toObject, ["personGeneration"], fromPersonGeneration)
    }

    let fromProminentPeople = getValueByPath(.object(fromObject), ["prominentPeople"])
    if case .null = fromProminentPeople {} else {
        try setValueByPath(&toObject, ["prominentPeople"], fromProminentPeople)
    }

    let fromOutputMimeType = getValueByPath(.object(fromObject), ["outputMimeType"])
    if case .null = fromOutputMimeType {} else {
        try setValueByPath(&toObject, ["imageOutputOptions", "mimeType"], fromOutputMimeType)
    }

    let fromOutputCompressionQuality = getValueByPath(.object(fromObject), ["outputCompressionQuality"])
    if case .null = fromOutputCompressionQuality {} else {
        try setValueByPath(&toObject, ["imageOutputOptions", "compressionQuality"], fromOutputCompressionQuality)
    }

    let fromImageOutputOptions = getValueByPath(.object(fromObject), ["imageOutputOptions"])
    if case .null = fromImageOutputOptions {} else {
        try setValueByPath(&toObject, ["imageOutputOptions"], fromImageOutputOptions)
    }

    return toObject
}

// MARK: - imageFromMldev

public func imageFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromImageBytes = getValueByPath(.object(fromObject), ["bytesBase64Encoded"])
    if case .null = fromImageBytes {} else {
        try setValueByPath(&toObject, ["imageBytes"], .string(try tBytes(fromImageBytes)))
    }

    let fromMimeType = getValueByPath(.object(fromObject), ["mimeType"])
    if case .null = fromMimeType {} else {
        try setValueByPath(&toObject, ["mimeType"], fromMimeType)
    }

    return toObject
}

// MARK: - imageFromVertex

public func imageFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromGcsUri = getValueByPath(.object(fromObject), ["gcsUri"])
    if case .null = fromGcsUri {} else {
        try setValueByPath(&toObject, ["gcsUri"], fromGcsUri)
    }

    let fromImageBytes = getValueByPath(.object(fromObject), ["bytesBase64Encoded"])
    if case .null = fromImageBytes {} else {
        try setValueByPath(&toObject, ["imageBytes"], .string(try tBytes(fromImageBytes)))
    }

    let fromMimeType = getValueByPath(.object(fromObject), ["mimeType"])
    if case .null = fromMimeType {} else {
        try setValueByPath(&toObject, ["mimeType"], fromMimeType)
    }

    return toObject
}

// MARK: - imageToMldev

public func imageToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let gcsUri = getValueByPath(.object(fromObject), ["gcsUri"])
    if case .null = gcsUri {} else {
        throw GenAIError.runtime("gcsUri parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let fromImageBytes = getValueByPath(.object(fromObject), ["imageBytes"])
    if case .null = fromImageBytes {} else {
        try setValueByPath(&toObject, ["bytesBase64Encoded"], .string(try tBytes(fromImageBytes)))
    }

    let fromMimeType = getValueByPath(.object(fromObject), ["mimeType"])
    if case .null = fromMimeType {} else {
        try setValueByPath(&toObject, ["mimeType"], fromMimeType)
    }

    return toObject
}

// MARK: - imageToVertex

public func imageToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromGcsUri = getValueByPath(.object(fromObject), ["gcsUri"])
    if case .null = fromGcsUri {} else {
        try setValueByPath(&toObject, ["gcsUri"], fromGcsUri)
    }

    let fromImageBytes = getValueByPath(.object(fromObject), ["imageBytes"])
    if case .null = fromImageBytes {} else {
        try setValueByPath(&toObject, ["bytesBase64Encoded"], .string(try tBytes(fromImageBytes)))
    }

    let fromMimeType = getValueByPath(.object(fromObject), ["mimeType"])
    if case .null = fromMimeType {} else {
        try setValueByPath(&toObject, ["mimeType"], fromMimeType)
    }

    return toObject
}

// MARK: - listModelsConfigToMldev

public func listModelsConfigToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromPageSize = getValueByPath(.object(fromObject), ["pageSize"])
    if case .null = fromPageSize {} else {
        try setValueByPath(&parentObject, ["_query", "pageSize"], fromPageSize)
    }

    let fromPageToken = getValueByPath(.object(fromObject), ["pageToken"])
    if case .null = fromPageToken {} else {
        try setValueByPath(&parentObject, ["_query", "pageToken"], fromPageToken)
    }

    let fromFilter = getValueByPath(.object(fromObject), ["filter"])
    if case .null = fromFilter {} else {
        try setValueByPath(&parentObject, ["_query", "filter"], fromFilter)
    }

    let fromQueryBase = getValueByPath(.object(fromObject), ["queryBase"])
    if case .null = fromQueryBase {} else {
        try setValueByPath(
            &parentObject,
            ["_url", "models_url"],
            .string(tModelsUrl(apiClient: apiClient, baseModels: fromQueryBase))
        )
    }

    return toObject
}

// MARK: - listModelsConfigToVertex

public func listModelsConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromPageSize = getValueByPath(.object(fromObject), ["pageSize"])
    if case .null = fromPageSize {} else {
        try setValueByPath(&parentObject, ["_query", "pageSize"], fromPageSize)
    }

    let fromPageToken = getValueByPath(.object(fromObject), ["pageToken"])
    if case .null = fromPageToken {} else {
        try setValueByPath(&parentObject, ["_query", "pageToken"], fromPageToken)
    }

    let fromFilter = getValueByPath(.object(fromObject), ["filter"])
    if case .null = fromFilter {} else {
        try setValueByPath(&parentObject, ["_query", "filter"], fromFilter)
    }

    let fromQueryBase = getValueByPath(.object(fromObject), ["queryBase"])
    if case .null = fromQueryBase {} else {
        try setValueByPath(
            &parentObject,
            ["_url", "models_url"],
            .string(tModelsUrl(apiClient: apiClient, baseModels: fromQueryBase))
        )
    }

    return toObject
}

// MARK: - listModelsParametersToMldev

public func listModelsParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try listModelsConfigToMldev(
            apiClient: apiClient,
            fromObject: configObj,
            parentObject: &toObject
        )
    }

    return toObject
}

// MARK: - listModelsParametersToVertex

public func listModelsParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try listModelsConfigToVertex(
            apiClient: apiClient,
            fromObject: configObj,
            parentObject: &toObject
        )
    }

    return toObject
}

// MARK: - listModelsResponseFromMldev

public func listModelsResponseFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    let fromNextPageToken = getValueByPath(.object(fromObject), ["nextPageToken"])
    if case .null = fromNextPageToken {} else {
        try setValueByPath(&toObject, ["nextPageToken"], fromNextPageToken)
    }

    let fromModels = getValueByPath(.object(fromObject), ["_self"])
    if case .null = fromModels {} else {
        let extracted = tExtractModels(fromModels)
        var transformed: [JSONValue] = []
        for item in extracted {
            var _dummyParent20: [String: JSONValue] = [:]
            let converted = try modelFromMldev(apiClient: apiClient, fromObject: item, parentObject: &_dummyParent20)
            transformed.append(.object(converted))
        }
        try setValueByPath(&toObject, ["models"], .array(transformed))
    }

    return toObject
}

// MARK: - listModelsResponseFromVertex

public func listModelsResponseFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    let fromNextPageToken = getValueByPath(.object(fromObject), ["nextPageToken"])
    if case .null = fromNextPageToken {} else {
        try setValueByPath(&toObject, ["nextPageToken"], fromNextPageToken)
    }

    let fromModels = getValueByPath(.object(fromObject), ["_self"])
    if case .null = fromModels {} else {
        let extracted = tExtractModels(fromModels)
        var transformed: [JSONValue] = []
        for item in extracted {
            var _dummyParent21: [String: JSONValue] = [:]
            let converted = try modelFromVertex(apiClient: apiClient, fromObject: item, parentObject: &_dummyParent21)
            transformed.append(.object(converted))
        }
        try setValueByPath(&toObject, ["models"], .array(transformed))
    }

    return toObject
}

// MARK: - maskReferenceConfigToVertex

public func maskReferenceConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromMaskMode = getValueByPath(.object(fromObject), ["maskMode"])
    if case .null = fromMaskMode {} else {
        try setValueByPath(&toObject, ["maskMode"], fromMaskMode)
    }

    let fromSegmentationClasses = getValueByPath(.object(fromObject), ["segmentationClasses"])
    if case .null = fromSegmentationClasses {} else {
        try setValueByPath(&toObject, ["maskClasses"], fromSegmentationClasses)
    }

    let fromMaskDilation = getValueByPath(.object(fromObject), ["maskDilation"])
    if case .null = fromMaskDilation {} else {
        try setValueByPath(&toObject, ["dilation"], fromMaskDilation)
    }

    return toObject
}

// MARK: - modelFromMldev

public func modelFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        try setValueByPath(&toObject, ["name"], fromName)
    }

    let fromDisplayName = getValueByPath(.object(fromObject), ["displayName"])
    if case .null = fromDisplayName {} else {
        try setValueByPath(&toObject, ["displayName"], fromDisplayName)
    }

    let fromDescription = getValueByPath(.object(fromObject), ["description"])
    if case .null = fromDescription {} else {
        try setValueByPath(&toObject, ["description"], fromDescription)
    }

    let fromVersion = getValueByPath(.object(fromObject), ["version"])
    if case .null = fromVersion {} else {
        try setValueByPath(&toObject, ["version"], fromVersion)
    }

    let fromTunedModelInfo = getValueByPath(.object(fromObject), ["_self"])
    if case .object(let tmiObj) = fromTunedModelInfo {
        var _dummyParent22: [String: JSONValue] = [:]
        let converted = try tunedModelInfoFromMldev(apiClient: apiClient, fromObject: tmiObj, parentObject: &_dummyParent22)
        try setValueByPath(&toObject, ["tunedModelInfo"], .object(converted))
    }

    let fromInputTokenLimit = getValueByPath(.object(fromObject), ["inputTokenLimit"])
    if case .null = fromInputTokenLimit {} else {
        try setValueByPath(&toObject, ["inputTokenLimit"], fromInputTokenLimit)
    }

    let fromOutputTokenLimit = getValueByPath(.object(fromObject), ["outputTokenLimit"])
    if case .null = fromOutputTokenLimit {} else {
        try setValueByPath(&toObject, ["outputTokenLimit"], fromOutputTokenLimit)
    }

    let fromSupportedActions = getValueByPath(.object(fromObject), ["supportedGenerationMethods"])
    if case .null = fromSupportedActions {} else {
        try setValueByPath(&toObject, ["supportedActions"], fromSupportedActions)
    }

    let fromTemperature = getValueByPath(.object(fromObject), ["temperature"])
    if case .null = fromTemperature {} else {
        try setValueByPath(&toObject, ["temperature"], fromTemperature)
    }

    let fromMaxTemperature = getValueByPath(.object(fromObject), ["maxTemperature"])
    if case .null = fromMaxTemperature {} else {
        try setValueByPath(&toObject, ["maxTemperature"], fromMaxTemperature)
    }

    let fromTopP = getValueByPath(.object(fromObject), ["topP"])
    if case .null = fromTopP {} else {
        try setValueByPath(&toObject, ["topP"], fromTopP)
    }

    let fromTopK = getValueByPath(.object(fromObject), ["topK"])
    if case .null = fromTopK {} else {
        try setValueByPath(&toObject, ["topK"], fromTopK)
    }

    let fromThinking = getValueByPath(.object(fromObject), ["thinking"])
    if case .null = fromThinking {} else {
        try setValueByPath(&toObject, ["thinking"], fromThinking)
    }

    return toObject
}

// MARK: - modelFromVertex

public func modelFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        try setValueByPath(&toObject, ["name"], fromName)
    }

    let fromDisplayName = getValueByPath(.object(fromObject), ["displayName"])
    if case .null = fromDisplayName {} else {
        try setValueByPath(&toObject, ["displayName"], fromDisplayName)
    }

    let fromDescription = getValueByPath(.object(fromObject), ["description"])
    if case .null = fromDescription {} else {
        try setValueByPath(&toObject, ["description"], fromDescription)
    }

    let fromVersion = getValueByPath(.object(fromObject), ["versionId"])
    if case .null = fromVersion {} else {
        try setValueByPath(&toObject, ["version"], fromVersion)
    }

    let fromEndpoints = getValueByPath(.object(fromObject), ["deployedModels"])
    if case .null = fromEndpoints {} else {
        if case .array(let arr) = fromEndpoints {
            var transformed: [JSONValue] = []
            for item in arr {
                if case .object(let itemObj) = item {
                    var _dummyParent23: [String: JSONValue] = [:]
                    let converted = try endpointFromVertex(apiClient: apiClient, fromObject: itemObj, parentObject: &_dummyParent23)
                    transformed.append(.object(converted))
                } else {
                    transformed.append(item)
                }
            }
            try setValueByPath(&toObject, ["endpoints"], .array(transformed))
        } else {
            try setValueByPath(&toObject, ["endpoints"], fromEndpoints)
        }
    }

    let fromLabels = getValueByPath(.object(fromObject), ["labels"])
    if case .null = fromLabels {} else {
        try setValueByPath(&toObject, ["labels"], fromLabels)
    }

    let fromTunedModelInfo = getValueByPath(.object(fromObject), ["_self"])
    if case .object(let tmiObj) = fromTunedModelInfo {
        var _dummyParent24: [String: JSONValue] = [:]
        let converted = try tunedModelInfoFromVertex(apiClient: apiClient, fromObject: tmiObj, parentObject: &_dummyParent24)
        try setValueByPath(&toObject, ["tunedModelInfo"], .object(converted))
    }

    let fromDefaultCheckpointId = getValueByPath(.object(fromObject), ["defaultCheckpointId"])
    if case .null = fromDefaultCheckpointId {} else {
        try setValueByPath(&toObject, ["defaultCheckpointId"], fromDefaultCheckpointId)
    }

    let fromCheckpoints = getValueByPath(.object(fromObject), ["checkpoints"])
    if case .null = fromCheckpoints {} else {
        try setValueByPath(&toObject, ["checkpoints"], fromCheckpoints)
    }

    return toObject
}

// MARK: - partToMldev

public func partToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromMediaResolution = getValueByPath(.object(fromObject), ["mediaResolution"])
    if case .null = fromMediaResolution {} else {
        try setValueByPath(&toObject, ["mediaResolution"], fromMediaResolution)
    }

    let fromCodeExecutionResult = getValueByPath(.object(fromObject), ["codeExecutionResult"])
    if case .null = fromCodeExecutionResult {} else {
        try setValueByPath(&toObject, ["codeExecutionResult"], fromCodeExecutionResult)
    }

    let fromExecutableCode = getValueByPath(.object(fromObject), ["executableCode"])
    if case .null = fromExecutableCode {} else {
        try setValueByPath(&toObject, ["executableCode"], fromExecutableCode)
    }

    let fromFileData = getValueByPath(.object(fromObject), ["fileData"])
    if case .object(let fdObj) = fromFileData {
        var _dummyParent25: [String: JSONValue] = [:]
        let converted = try fileDataToMldev(apiClient: apiClient, fromObject: fdObj, parentObject: &_dummyParent25)
        try setValueByPath(&toObject, ["fileData"], .object(converted))
    }

    let fromFunctionCall = getValueByPath(.object(fromObject), ["functionCall"])
    if case .object(let fcObj) = fromFunctionCall {
        var _dummyParent26: [String: JSONValue] = [:]
        let converted = try functionCallToMldev(apiClient: apiClient, fromObject: fcObj, parentObject: &_dummyParent26)
        try setValueByPath(&toObject, ["functionCall"], .object(converted))
    }

    let fromFunctionResponse = getValueByPath(.object(fromObject), ["functionResponse"])
    if case .null = fromFunctionResponse {} else {
        try setValueByPath(&toObject, ["functionResponse"], fromFunctionResponse)
    }

    let fromInlineData = getValueByPath(.object(fromObject), ["inlineData"])
    if case .object(let idObj) = fromInlineData {
        var _dummyParent27: [String: JSONValue] = [:]
        let converted = try blobToMldev(apiClient: apiClient, fromObject: idObj, parentObject: &_dummyParent27)
        try setValueByPath(&toObject, ["inlineData"], .object(converted))
    }

    let fromText = getValueByPath(.object(fromObject), ["text"])
    if case .null = fromText {} else {
        try setValueByPath(&toObject, ["text"], fromText)
    }

    let fromThought = getValueByPath(.object(fromObject), ["thought"])
    if case .null = fromThought {} else {
        try setValueByPath(&toObject, ["thought"], fromThought)
    }

    let fromThoughtSignature = getValueByPath(.object(fromObject), ["thoughtSignature"])
    if case .null = fromThoughtSignature {} else {
        try setValueByPath(&toObject, ["thoughtSignature"], fromThoughtSignature)
    }

    let fromVideoMetadata = getValueByPath(.object(fromObject), ["videoMetadata"])
    if case .null = fromVideoMetadata {} else {
        try setValueByPath(&toObject, ["videoMetadata"], fromVideoMetadata)
    }

    let fromToolCall = getValueByPath(.object(fromObject), ["toolCall"])
    if case .null = fromToolCall {} else {
        try setValueByPath(&toObject, ["toolCall"], fromToolCall)
    }

    let fromToolResponse = getValueByPath(.object(fromObject), ["toolResponse"])
    if case .null = fromToolResponse {} else {
        try setValueByPath(&toObject, ["toolResponse"], fromToolResponse)
    }

    let fromPartMetadata = getValueByPath(.object(fromObject), ["partMetadata"])
    if case .null = fromPartMetadata {} else {
        try setValueByPath(&toObject, ["partMetadata"], fromPartMetadata)
    }

    return toObject
}

// MARK: - codeExecutionResultToVertex

public func codeExecutionResultToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromOutcome = getValueByPath(.object(fromObject), ["outcome"])
    if case .null = fromOutcome {} else {
        try setValueByPath(&toObject, ["outcome"], fromOutcome)
    }

    let fromOutput = getValueByPath(.object(fromObject), ["output"])
    if case .null = fromOutput {} else {
        try setValueByPath(&toObject, ["output"], fromOutput)
    }

    let id = getValueByPath(.object(fromObject), ["id"])
    if case .null = id {} else {
        throw GenAIError.runtime("id parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode.")
    }

    return toObject
}

// MARK: - executableCodeToVertex

public func executableCodeToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromCode = getValueByPath(.object(fromObject), ["code"])
    if case .null = fromCode {} else {
        try setValueByPath(&toObject, ["code"], fromCode)
    }

    let fromLanguage = getValueByPath(.object(fromObject), ["language"])
    if case .null = fromLanguage {} else {
        try setValueByPath(&toObject, ["language"], fromLanguage)
    }

    let id = getValueByPath(.object(fromObject), ["id"])
    if case .null = id {} else {
        throw GenAIError.runtime("id parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode.")
    }

    return toObject
}

// MARK: - computerUseToVertex

public func computerUseToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromEnvironment = getValueByPath(.object(fromObject), ["environment"])
    if case .null = fromEnvironment {} else {
        try setValueByPath(&toObject, ["environment"], fromEnvironment)
    }

    let fromExcludedPredefinedFunctions = getValueByPath(.object(fromObject), ["excludedPredefinedFunctions"])
    if case .null = fromExcludedPredefinedFunctions {} else {
        try setValueByPath(&toObject, ["excludedPredefinedFunctions"], fromExcludedPredefinedFunctions)
    }

    let enablePromptInjectionDetection = getValueByPath(.object(fromObject), ["enablePromptInjectionDetection"])
    if case .null = enablePromptInjectionDetection {} else {
        throw GenAIError.runtime("enablePromptInjectionDetection parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode.")
    }

    return toObject
}

// MARK: - partToVertex

public func partToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromMediaResolution = getValueByPath(.object(fromObject), ["mediaResolution"])
    if case .null = fromMediaResolution {} else {
        try setValueByPath(&toObject, ["mediaResolution"], fromMediaResolution)
    }

    let fromCodeExecutionResult = getValueByPath(.object(fromObject), ["codeExecutionResult"])
    if case .null = fromCodeExecutionResult {} else {
        var fromCodeExecutionResultObj = fromCodeExecutionResult
        if case .object(let dict) = fromCodeExecutionResult {
            var parentCopy = parentObject
            let result = try codeExecutionResultToVertex(apiClient: apiClient, fromObject: dict, parentObject: &parentCopy)
            fromCodeExecutionResultObj = .object(result)
        }
        try setValueByPath(&toObject, ["codeExecutionResult"], fromCodeExecutionResultObj)
    }

    let fromExecutableCode = getValueByPath(.object(fromObject), ["executableCode"])
    if case .null = fromExecutableCode {} else {
        var fromExecutableCodeObj = fromExecutableCode
        if case .object(let dict) = fromExecutableCode {
            var parentCopy = parentObject
            let result = try executableCodeToVertex(apiClient: apiClient, fromObject: dict, parentObject: &parentCopy)
            fromExecutableCodeObj = .object(result)
        }
        try setValueByPath(&toObject, ["executableCode"], fromExecutableCodeObj)
    }

    let fromFileData = getValueByPath(.object(fromObject), ["fileData"])
    if case .null = fromFileData {} else {
        try setValueByPath(&toObject, ["fileData"], fromFileData)
    }

    let fromFunctionCall = getValueByPath(.object(fromObject), ["functionCall"])
    if case .null = fromFunctionCall {} else {
        try setValueByPath(&toObject, ["functionCall"], fromFunctionCall)
    }

    let fromFunctionResponse = getValueByPath(.object(fromObject), ["functionResponse"])
    if case .null = fromFunctionResponse {} else {
        try setValueByPath(&toObject, ["functionResponse"], fromFunctionResponse)
    }

    let fromInlineData = getValueByPath(.object(fromObject), ["inlineData"])
    if case .null = fromInlineData {} else {
        try setValueByPath(&toObject, ["inlineData"], fromInlineData)
    }

    let fromText = getValueByPath(.object(fromObject), ["text"])
    if case .null = fromText {} else {
        try setValueByPath(&toObject, ["text"], fromText)
    }

    let fromThought = getValueByPath(.object(fromObject), ["thought"])
    if case .null = fromThought {} else {
        try setValueByPath(&toObject, ["thought"], fromThought)
    }

    let fromThoughtSignature = getValueByPath(.object(fromObject), ["thoughtSignature"])
    if case .null = fromThoughtSignature {} else {
        try setValueByPath(&toObject, ["thoughtSignature"], fromThoughtSignature)
    }

    let fromVideoMetadata = getValueByPath(.object(fromObject), ["videoMetadata"])
    if case .null = fromVideoMetadata {} else {
        try setValueByPath(&toObject, ["videoMetadata"], fromVideoMetadata)
    }

    let toolCall = getValueByPath(.object(fromObject), ["toolCall"])
    if case .null = toolCall {} else {
        throw GenAIError.runtime("toolCall parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode.")
    }

    let toolResponse = getValueByPath(.object(fromObject), ["toolResponse"])
    if case .null = toolResponse {} else {
        throw GenAIError.runtime("toolResponse parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode.")
    }

    let partMetadata = getValueByPath(.object(fromObject), ["partMetadata"])
    if case .null = partMetadata {} else {
        throw GenAIError.runtime("partMetadata parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode.")
    }

    return toObject
}

// MARK: - productImageToVertex

public func productImageToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromProductImage = getValueByPath(.object(fromObject), ["productImage"])
    if case .object(let piObj) = fromProductImage {
        var _dummyParent28: [String: JSONValue] = [:]
        let converted = try imageToVertex(apiClient: apiClient, fromObject: piObj, parentObject: &_dummyParent28)
        try setValueByPath(&toObject, ["image"], .object(converted))
    }

    return toObject
}

// MARK: - recontextImageConfigToVertex

public func recontextImageConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromNumberOfImages = getValueByPath(.object(fromObject), ["numberOfImages"])
    if case .null = fromNumberOfImages {} else {
        try setValueByPath(&parentObject, ["parameters", "sampleCount"], fromNumberOfImages)
    }

    let fromBaseSteps = getValueByPath(.object(fromObject), ["baseSteps"])
    if case .null = fromBaseSteps {} else {
        try setValueByPath(&parentObject, ["parameters", "baseSteps"], fromBaseSteps)
    }

    let fromOutputGcsUri = getValueByPath(.object(fromObject), ["outputGcsUri"])
    if case .null = fromOutputGcsUri {} else {
        try setValueByPath(&parentObject, ["parameters", "storageUri"], fromOutputGcsUri)
    }

    let fromSeed = getValueByPath(.object(fromObject), ["seed"])
    if case .null = fromSeed {} else {
        try setValueByPath(&parentObject, ["parameters", "seed"], fromSeed)
    }

    let fromSafetyFilterLevel = getValueByPath(.object(fromObject), ["safetyFilterLevel"])
    if case .null = fromSafetyFilterLevel {} else {
        try setValueByPath(&parentObject, ["parameters", "safetySetting"], fromSafetyFilterLevel)
    }

    let fromPersonGeneration = getValueByPath(.object(fromObject), ["personGeneration"])
    if case .null = fromPersonGeneration {} else {
        try setValueByPath(&parentObject, ["parameters", "personGeneration"], fromPersonGeneration)
    }

    let fromAddWatermark = getValueByPath(.object(fromObject), ["addWatermark"])
    if case .null = fromAddWatermark {} else {
        try setValueByPath(&parentObject, ["parameters", "addWatermark"], fromAddWatermark)
    }

    let fromOutputMimeType = getValueByPath(.object(fromObject), ["outputMimeType"])
    if case .null = fromOutputMimeType {} else {
        try setValueByPath(&parentObject, ["parameters", "outputOptions", "mimeType"], fromOutputMimeType)
    }

    let fromOutputCompressionQuality = getValueByPath(.object(fromObject), ["outputCompressionQuality"])
    if case .null = fromOutputCompressionQuality {} else {
        try setValueByPath(&parentObject, ["parameters", "outputOptions", "compressionQuality"], fromOutputCompressionQuality)
    }

    let fromEnhancePrompt = getValueByPath(.object(fromObject), ["enhancePrompt"])
    if case .null = fromEnhancePrompt {} else {
        try setValueByPath(&parentObject, ["parameters", "enhancePrompt"], fromEnhancePrompt)
    }

    let fromLabels = getValueByPath(.object(fromObject), ["labels"])
    if case .null = fromLabels {} else {
        try setValueByPath(&parentObject, ["labels"], fromLabels)
    }

    return toObject
}

// MARK: - recontextImageParametersToVertex

public func recontextImageParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        try setValueByPath(&toObject, ["_url", "model"], .string(try tModel(apiClient: apiClient, model: fromModel)))
    }

    let fromSource = getValueByPath(.object(fromObject), ["source"])
    if case .object(let srcObj) = fromSource {
        _ = try recontextImageSourceToVertex(apiClient: apiClient, fromObject: srcObj, parentObject: &toObject)
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let cfgObj) = fromConfig {
        _ = try recontextImageConfigToVertex(apiClient: apiClient, fromObject: cfgObj, parentObject: &toObject)
    }

    return toObject
}

// MARK: - recontextImageResponseFromVertex

public func recontextImageResponseFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromGeneratedImages = getValueByPath(.object(fromObject), ["predictions"])
    if case .null = fromGeneratedImages {} else {
        if case .array(let arr) = fromGeneratedImages {
            var transformed: [JSONValue] = []
            for item in arr {
                if case .object(let itemObj) = item {
                    var _dummyParent29: [String: JSONValue] = [:]
                    let converted = try generatedImageFromVertex(apiClient: apiClient, fromObject: itemObj, parentObject: &_dummyParent29)
                    transformed.append(.object(converted))
                } else {
                    transformed.append(item)
                }
            }
            try setValueByPath(&toObject, ["generatedImages"], .array(transformed))
        } else {
            try setValueByPath(&toObject, ["generatedImages"], fromGeneratedImages)
        }
    }

    return toObject
}

// MARK: - recontextImageSourceToVertex

public func recontextImageSourceToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromPrompt = getValueByPath(.object(fromObject), ["prompt"])
    if case .null = fromPrompt {} else {
        try setValueByPath(&parentObject, ["instances[0]", "prompt"], fromPrompt)
    }

    let fromPersonImage = getValueByPath(.object(fromObject), ["personImage"])
    if case .object(let piObj) = fromPersonImage {
        var _dummyParent30: [String: JSONValue] = [:]
        let converted = try imageToVertex(apiClient: apiClient, fromObject: piObj, parentObject: &_dummyParent30)
        try setValueByPath(&parentObject, ["instances[0]", "personImage", "image"], .object(converted))
    }

    let fromProductImages = getValueByPath(.object(fromObject), ["productImages"])
    if case .null = fromProductImages {} else {
        if case .array(let arr) = fromProductImages {
            var transformed: [JSONValue] = []
            for item in arr {
                if case .object(let itemObj) = item {
                    var _dummyParent31: [String: JSONValue] = [:]
                    let converted = try productImageToVertex(apiClient: apiClient, fromObject: itemObj, parentObject: &_dummyParent31)
                    transformed.append(.object(converted))
                } else {
                    transformed.append(item)
                }
            }
            try setValueByPath(&parentObject, ["instances[0]", "productImages"], .array(transformed))
        } else {
            try setValueByPath(&parentObject, ["instances[0]", "productImages"], fromProductImages)
        }
    }

    return toObject
}

// MARK: - referenceImageAPIInternalToVertex

public func referenceImageAPIInternalToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromReferenceImage = getValueByPath(.object(fromObject), ["referenceImage"])
    if case .object(let riObj) = fromReferenceImage {
        var _dummyParent32: [String: JSONValue] = [:]
        let converted = try imageToVertex(apiClient: apiClient, fromObject: riObj, parentObject: &_dummyParent32)
        try setValueByPath(&toObject, ["referenceImage"], .object(converted))
    }

    let fromReferenceId = getValueByPath(.object(fromObject), ["referenceId"])
    if case .null = fromReferenceId {} else {
        try setValueByPath(&toObject, ["referenceId"], fromReferenceId)
    }

    let fromReferenceType = getValueByPath(.object(fromObject), ["referenceType"])
    if case .null = fromReferenceType {} else {
        try setValueByPath(&toObject, ["referenceType"], fromReferenceType)
    }

    let fromMaskImageConfig = getValueByPath(.object(fromObject), ["maskImageConfig"])
    if case .object(let micObj) = fromMaskImageConfig {
        var _dummyParent33: [String: JSONValue] = [:]
        let converted = try maskReferenceConfigToVertex(apiClient: apiClient, fromObject: micObj, parentObject: &_dummyParent33)
        try setValueByPath(&toObject, ["maskImageConfig"], .object(converted))
    }

    let fromControlImageConfig = getValueByPath(.object(fromObject), ["controlImageConfig"])
    if case .object(let cicObj) = fromControlImageConfig {
        var _dummyParent34: [String: JSONValue] = [:]
        let converted = try controlReferenceConfigToVertex(apiClient: apiClient, fromObject: cicObj, parentObject: &_dummyParent34)
        try setValueByPath(&toObject, ["controlImageConfig"], .object(converted))
    }

    let fromStyleImageConfig = getValueByPath(.object(fromObject), ["styleImageConfig"])
    if case .null = fromStyleImageConfig {} else {
        try setValueByPath(&toObject, ["styleImageConfig"], fromStyleImageConfig)
    }

    let fromSubjectImageConfig = getValueByPath(.object(fromObject), ["subjectImageConfig"])
    if case .null = fromSubjectImageConfig {} else {
        try setValueByPath(&toObject, ["subjectImageConfig"], fromSubjectImageConfig)
    }

    return toObject
}

// MARK: - safetyAttributesFromMldev

public func safetyAttributesFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromCategories = getValueByPath(.object(fromObject), ["safetyAttributes", "categories"])
    if case .null = fromCategories {} else {
        try setValueByPath(&toObject, ["categories"], fromCategories)
    }

    let fromScores = getValueByPath(.object(fromObject), ["safetyAttributes", "scores"])
    if case .null = fromScores {} else {
        try setValueByPath(&toObject, ["scores"], fromScores)
    }

    let fromContentType = getValueByPath(.object(fromObject), ["contentType"])
    if case .null = fromContentType {} else {
        try setValueByPath(&toObject, ["contentType"], fromContentType)
    }

    return toObject
}

// MARK: - safetyAttributesFromVertex

public func safetyAttributesFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromCategories = getValueByPath(.object(fromObject), ["safetyAttributes", "categories"])
    if case .null = fromCategories {} else {
        try setValueByPath(&toObject, ["categories"], fromCategories)
    }

    let fromScores = getValueByPath(.object(fromObject), ["safetyAttributes", "scores"])
    if case .null = fromScores {} else {
        try setValueByPath(&toObject, ["scores"], fromScores)
    }

    let fromContentType = getValueByPath(.object(fromObject), ["contentType"])
    if case .null = fromContentType {} else {
        try setValueByPath(&toObject, ["contentType"], fromContentType)
    }

    return toObject
}

// MARK: - safetySettingToMldev

public func safetySettingToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromCategory = getValueByPath(.object(fromObject), ["category"])
    if case .null = fromCategory {} else {
        try setValueByPath(&toObject, ["category"], fromCategory)
    }

    let method = getValueByPath(.object(fromObject), ["method"])
    if case .null = method {} else {
        throw GenAIError.runtime("method parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let fromThreshold = getValueByPath(.object(fromObject), ["threshold"])
    if case .null = fromThreshold {} else {
        try setValueByPath(&toObject, ["threshold"], fromThreshold)
    }

    return toObject
}

// MARK: - scribbleImageToVertex

public func scribbleImageToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromImage = getValueByPath(.object(fromObject), ["image"])
    if case .object(let imgObj) = fromImage {
        var _dummyParent35: [String: JSONValue] = [:]
        let converted = try imageToVertex(apiClient: apiClient, fromObject: imgObj, parentObject: &_dummyParent35)
        try setValueByPath(&toObject, ["image"], .object(converted))
    }

    return toObject
}

// MARK: - segmentImageConfigToVertex

public func segmentImageConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromMode = getValueByPath(.object(fromObject), ["mode"])
    if case .null = fromMode {} else {
        try setValueByPath(&parentObject, ["parameters", "mode"], fromMode)
    }

    let fromMaxPredictions = getValueByPath(.object(fromObject), ["maxPredictions"])
    if case .null = fromMaxPredictions {} else {
        try setValueByPath(&parentObject, ["parameters", "maxPredictions"], fromMaxPredictions)
    }

    let fromConfidenceThreshold = getValueByPath(.object(fromObject), ["confidenceThreshold"])
    if case .null = fromConfidenceThreshold {} else {
        try setValueByPath(&parentObject, ["parameters", "confidenceThreshold"], fromConfidenceThreshold)
    }

    let fromMaskDilation = getValueByPath(.object(fromObject), ["maskDilation"])
    if case .null = fromMaskDilation {} else {
        try setValueByPath(&parentObject, ["parameters", "maskDilation"], fromMaskDilation)
    }

    let fromBinaryColorThreshold = getValueByPath(.object(fromObject), ["binaryColorThreshold"])
    if case .null = fromBinaryColorThreshold {} else {
        try setValueByPath(&parentObject, ["parameters", "binaryColorThreshold"], fromBinaryColorThreshold)
    }

    let fromLabels = getValueByPath(.object(fromObject), ["labels"])
    if case .null = fromLabels {} else {
        try setValueByPath(&parentObject, ["labels"], fromLabels)
    }

    return toObject
}

// MARK: - segmentImageParametersToVertex

public func segmentImageParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        try setValueByPath(&toObject, ["_url", "model"], .string(try tModel(apiClient: apiClient, model: fromModel)))
    }

    let fromSource = getValueByPath(.object(fromObject), ["source"])
    if case .object(let srcObj) = fromSource {
        _ = try segmentImageSourceToVertex(apiClient: apiClient, fromObject: srcObj, parentObject: &toObject)
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let cfgObj) = fromConfig {
        _ = try segmentImageConfigToVertex(apiClient: apiClient, fromObject: cfgObj, parentObject: &toObject)
    }

    return toObject
}

// MARK: - segmentImageResponseFromVertex

public func segmentImageResponseFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromGeneratedMasks = getValueByPath(.object(fromObject), ["predictions"])
    if case .null = fromGeneratedMasks {} else {
        if case .array(let arr) = fromGeneratedMasks {
            var transformed: [JSONValue] = []
            for item in arr {
                if case .object(let itemObj) = item {
                    var _dummyParent36: [String: JSONValue] = [:]
                    let converted = try generatedImageMaskFromVertex(apiClient: apiClient, fromObject: itemObj, parentObject: &_dummyParent36)
                    transformed.append(.object(converted))
                } else {
                    transformed.append(item)
                }
            }
            try setValueByPath(&toObject, ["generatedMasks"], .array(transformed))
        } else {
            try setValueByPath(&toObject, ["generatedMasks"], fromGeneratedMasks)
        }
    }

    return toObject
}

// MARK: - segmentImageSourceToVertex

public func segmentImageSourceToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromPrompt = getValueByPath(.object(fromObject), ["prompt"])
    if case .null = fromPrompt {} else {
        try setValueByPath(&parentObject, ["instances[0]", "prompt"], fromPrompt)
    }

    let fromImage = getValueByPath(.object(fromObject), ["image"])
    if case .object(let imgObj) = fromImage {
        var _dummyParent37: [String: JSONValue] = [:]
        let converted = try imageToVertex(apiClient: apiClient, fromObject: imgObj, parentObject: &_dummyParent37)
        try setValueByPath(&parentObject, ["instances[0]", "image"], .object(converted))
    }

    let fromScribbleImage = getValueByPath(.object(fromObject), ["scribbleImage"])
    if case .object(let siObj) = fromScribbleImage {
        var _dummyParent38: [String: JSONValue] = [:]
        let converted = try scribbleImageToVertex(apiClient: apiClient, fromObject: siObj, parentObject: &_dummyParent38)
        try setValueByPath(&parentObject, ["instances[0]", "scribble"], .object(converted))
    }

    return toObject
}

// MARK: - toolConfigToMldev

public func toolConfigToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromRetrievalConfig = getValueByPath(.object(fromObject), ["retrievalConfig"])
    if case .null = fromRetrievalConfig {} else {
        try setValueByPath(&toObject, ["retrievalConfig"], fromRetrievalConfig)
    }

    let fromFunctionCallingConfig = getValueByPath(.object(fromObject), ["functionCallingConfig"])
    if case .object(let fccObj) = fromFunctionCallingConfig {
        var _dummyParent39: [String: JSONValue] = [:]
        let converted = try functionCallingConfigToMldev(apiClient: apiClient, fromObject: fccObj, parentObject: &_dummyParent39)
        try setValueByPath(&toObject, ["functionCallingConfig"], .object(converted))
    }

    let fromIncludeServerSideToolInvocations = getValueByPath(.object(fromObject), ["includeServerSideToolInvocations"])
    if case .null = fromIncludeServerSideToolInvocations {} else {
        try setValueByPath(&toObject, ["includeServerSideToolInvocations"], fromIncludeServerSideToolInvocations)
    }

    return toObject
}

// MARK: - toolConfigToVertex

public func toolConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromRetrievalConfig = getValueByPath(.object(fromObject), ["retrievalConfig"])
    if case .null = fromRetrievalConfig {} else {
        try setValueByPath(&toObject, ["retrievalConfig"], fromRetrievalConfig)
    }

    let fromFunctionCallingConfig = getValueByPath(.object(fromObject), ["functionCallingConfig"])
    if case .null = fromFunctionCallingConfig {} else {
        try setValueByPath(&toObject, ["functionCallingConfig"], fromFunctionCallingConfig)
    }

    let includeServerSideToolInvocations = getValueByPath(.object(fromObject), ["includeServerSideToolInvocations"])
    if case .null = includeServerSideToolInvocations {} else {
        throw GenAIError.runtime("includeServerSideToolInvocations parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode.")
    }

    return toObject
}

// MARK: - toolToMldev

public func toolToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let retrieval = getValueByPath(.object(fromObject), ["retrieval"])
    if case .null = retrieval {} else {
        throw GenAIError.runtime("retrieval parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let fromComputerUse = getValueByPath(.object(fromObject), ["computerUse"])
    if case .null = fromComputerUse {} else {
        try setValueByPath(&toObject, ["computerUse"], fromComputerUse)
    }

    let fromFileSearch = getValueByPath(.object(fromObject), ["fileSearch"])
    if case .null = fromFileSearch {} else {
        try setValueByPath(&toObject, ["fileSearch"], fromFileSearch)
    }

    let fromGoogleSearch = getValueByPath(.object(fromObject), ["googleSearch"])
    if case .object(let gsObj) = fromGoogleSearch {
        var _dummyParent40: [String: JSONValue] = [:]
        let converted = try googleSearchToMldev(apiClient: apiClient, fromObject: gsObj, parentObject: &_dummyParent40)
        try setValueByPath(&toObject, ["googleSearch"], .object(converted))
    }

    let fromGoogleMaps = getValueByPath(.object(fromObject), ["googleMaps"])
    if case .object(let gmObj) = fromGoogleMaps {
        var _dummyParent41: [String: JSONValue] = [:]
        let converted = try googleMapsToMldev(apiClient: apiClient, fromObject: gmObj, parentObject: &_dummyParent41)
        try setValueByPath(&toObject, ["googleMaps"], .object(converted))
    }

    let fromCodeExecution = getValueByPath(.object(fromObject), ["codeExecution"])
    if case .null = fromCodeExecution {} else {
        try setValueByPath(&toObject, ["codeExecution"], fromCodeExecution)
    }

    let enterpriseWebSearch = getValueByPath(.object(fromObject), ["enterpriseWebSearch"])
    if case .null = enterpriseWebSearch {} else {
        throw GenAIError.runtime("enterpriseWebSearch parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let fromFunctionDeclarations = getValueByPath(.object(fromObject), ["functionDeclarations"])
    if case .null = fromFunctionDeclarations {} else {
        try setValueByPath(&toObject, ["functionDeclarations"], fromFunctionDeclarations)
    }

    let fromGoogleSearchRetrieval = getValueByPath(.object(fromObject), ["googleSearchRetrieval"])
    if case .null = fromGoogleSearchRetrieval {} else {
        try setValueByPath(&toObject, ["googleSearchRetrieval"], fromGoogleSearchRetrieval)
    }

    let parallelAiSearch = getValueByPath(.object(fromObject), ["parallelAiSearch"])
    if case .null = parallelAiSearch {} else {
        throw GenAIError.runtime("parallelAiSearch parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode.")
    }

    let fromUrlContext = getValueByPath(.object(fromObject), ["urlContext"])
    if case .null = fromUrlContext {} else {
        try setValueByPath(&toObject, ["urlContext"], fromUrlContext)
    }

    let fromMcpServers = getValueByPath(.object(fromObject), ["mcpServers"])
    if case .null = fromMcpServers {} else {
        try setValueByPath(&toObject, ["mcpServers"], fromMcpServers)
    }

    return toObject
}

// MARK: - toolToVertex

public func toolToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromRetrieval = getValueByPath(.object(fromObject), ["retrieval"])
    if case .null = fromRetrieval {} else {
        try setValueByPath(&toObject, ["retrieval"], fromRetrieval)
    }

    let fromComputerUse = getValueByPath(.object(fromObject), ["computerUse"])
    if case .null = fromComputerUse {} else {
        var fromComputerUseObj = fromComputerUse
        if case .object(let dict) = fromComputerUse {
            var parentCopy = parentObject
            let result = try computerUseToVertex(apiClient: apiClient, fromObject: dict, parentObject: &parentCopy)
            fromComputerUseObj = .object(result)
        }
        try setValueByPath(&toObject, ["computerUse"], fromComputerUseObj)
    }

    let fileSearch = getValueByPath(.object(fromObject), ["fileSearch"])
    if case .null = fileSearch {} else {
        throw GenAIError.runtime("fileSearch parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode.")
    }

    let fromGoogleSearch = getValueByPath(.object(fromObject), ["googleSearch"])
    if case .null = fromGoogleSearch {} else {
        try setValueByPath(&toObject, ["googleSearch"], fromGoogleSearch)
    }

    let fromGoogleMaps = getValueByPath(.object(fromObject), ["googleMaps"])
    if case .null = fromGoogleMaps {} else {
        try setValueByPath(&toObject, ["googleMaps"], fromGoogleMaps)
    }

    let fromCodeExecution = getValueByPath(.object(fromObject), ["codeExecution"])
    if case .null = fromCodeExecution {} else {
        try setValueByPath(&toObject, ["codeExecution"], fromCodeExecution)
    }

    let fromEnterpriseWebSearch = getValueByPath(.object(fromObject), ["enterpriseWebSearch"])
    if case .null = fromEnterpriseWebSearch {} else {
        try setValueByPath(&toObject, ["enterpriseWebSearch"], fromEnterpriseWebSearch)
    }

    let fromFunctionDeclarations = getValueByPath(.object(fromObject), ["functionDeclarations"])
    if case .null = fromFunctionDeclarations {} else {
        try setValueByPath(&toObject, ["functionDeclarations"], fromFunctionDeclarations)
    }

    let fromGoogleSearchRetrieval = getValueByPath(.object(fromObject), ["googleSearchRetrieval"])
    if case .null = fromGoogleSearchRetrieval {} else {
        try setValueByPath(&toObject, ["googleSearchRetrieval"], fromGoogleSearchRetrieval)
    }

    let fromParallelAiSearch = getValueByPath(.object(fromObject), ["parallelAiSearch"])
    if case .null = fromParallelAiSearch {} else {
        try setValueByPath(&toObject, ["parallelAiSearch"], fromParallelAiSearch)
    }

    let fromUrlContext = getValueByPath(.object(fromObject), ["urlContext"])
    if case .null = fromUrlContext {} else {
        try setValueByPath(&toObject, ["urlContext"], fromUrlContext)
    }

    let mcpServers = getValueByPath(.object(fromObject), ["mcpServers"])
    if case .null = mcpServers {} else {
        throw GenAIError.runtime("mcpServers parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode.")
    }

    return toObject
}

// MARK: - tunedModelInfoFromMldev

public func tunedModelInfoFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromBaseModel = getValueByPath(.object(fromObject), ["baseModel"])
    if case .null = fromBaseModel {} else {
        try setValueByPath(&toObject, ["baseModel"], fromBaseModel)
    }

    let fromCreateTime = getValueByPath(.object(fromObject), ["createTime"])
    if case .null = fromCreateTime {} else {
        try setValueByPath(&toObject, ["createTime"], fromCreateTime)
    }

    let fromUpdateTime = getValueByPath(.object(fromObject), ["updateTime"])
    if case .null = fromUpdateTime {} else {
        try setValueByPath(&toObject, ["updateTime"], fromUpdateTime)
    }

    return toObject
}

// MARK: - tunedModelInfoFromVertex

public func tunedModelInfoFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromBaseModel = getValueByPath(
        .object(fromObject),
        ["labels", "google-vertex-llm-tuning-base-model-id"]
    )
    if case .null = fromBaseModel {} else {
        try setValueByPath(&toObject, ["baseModel"], fromBaseModel)
    }

    let fromCreateTime = getValueByPath(.object(fromObject), ["createTime"])
    if case .null = fromCreateTime {} else {
        try setValueByPath(&toObject, ["createTime"], fromCreateTime)
    }

    let fromUpdateTime = getValueByPath(.object(fromObject), ["updateTime"])
    if case .null = fromUpdateTime {} else {
        try setValueByPath(&toObject, ["updateTime"], fromUpdateTime)
    }

    return toObject
}

// MARK: - updateModelConfigToMldev

public func updateModelConfigToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromDisplayName = getValueByPath(.object(fromObject), ["displayName"])
    if case .null = fromDisplayName {} else {
        try setValueByPath(&parentObject, ["displayName"], fromDisplayName)
    }

    let fromDescription = getValueByPath(.object(fromObject), ["description"])
    if case .null = fromDescription {} else {
        try setValueByPath(&parentObject, ["description"], fromDescription)
    }

    let fromDefaultCheckpointId = getValueByPath(.object(fromObject), ["defaultCheckpointId"])
    if case .null = fromDefaultCheckpointId {} else {
        try setValueByPath(&parentObject, ["defaultCheckpointId"], fromDefaultCheckpointId)
    }

    return toObject
}

// MARK: - updateModelConfigToVertex

public func updateModelConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromDisplayName = getValueByPath(.object(fromObject), ["displayName"])
    if case .null = fromDisplayName {} else {
        try setValueByPath(&parentObject, ["displayName"], fromDisplayName)
    }

    let fromDescription = getValueByPath(.object(fromObject), ["description"])
    if case .null = fromDescription {} else {
        try setValueByPath(&parentObject, ["description"], fromDescription)
    }

    let fromDefaultCheckpointId = getValueByPath(.object(fromObject), ["defaultCheckpointId"])
    if case .null = fromDefaultCheckpointId {} else {
        try setValueByPath(&parentObject, ["defaultCheckpointId"], fromDefaultCheckpointId)
    }

    return toObject
}

// MARK: - updateModelParametersToMldev

public func updateModelParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        try setValueByPath(&toObject, ["_url", "name"], .string(try tModel(apiClient: apiClient, model: fromModel)))
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let cfgObj) = fromConfig {
        _ = try updateModelConfigToMldev(apiClient: apiClient, fromObject: cfgObj, parentObject: &toObject)
    }

    return toObject
}

// MARK: - updateModelParametersToVertex

public func updateModelParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        try setValueByPath(&toObject, ["_url", "model"], .string(try tModel(apiClient: apiClient, model: fromModel)))
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let cfgObj) = fromConfig {
        _ = try updateModelConfigToVertex(apiClient: apiClient, fromObject: cfgObj, parentObject: &toObject)
    }

    return toObject
}

// MARK: - upscaleImageAPIConfigInternalToVertex

public func upscaleImageAPIConfigInternalToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    let toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromOutputGcsUri = getValueByPath(.object(fromObject), ["outputGcsUri"])
    if case .null = fromOutputGcsUri {} else {
        try setValueByPath(&parentObject, ["parameters", "storageUri"], fromOutputGcsUri)
    }

    let fromSafetyFilterLevel = getValueByPath(.object(fromObject), ["safetyFilterLevel"])
    if case .null = fromSafetyFilterLevel {} else {
        try setValueByPath(&parentObject, ["parameters", "safetySetting"], fromSafetyFilterLevel)
    }

    let fromPersonGeneration = getValueByPath(.object(fromObject), ["personGeneration"])
    if case .null = fromPersonGeneration {} else {
        try setValueByPath(&parentObject, ["parameters", "personGeneration"], fromPersonGeneration)
    }

    let fromIncludeRaiReason = getValueByPath(.object(fromObject), ["includeRaiReason"])
    if case .null = fromIncludeRaiReason {} else {
        try setValueByPath(&parentObject, ["parameters", "includeRaiReason"], fromIncludeRaiReason)
    }

    let fromOutputMimeType = getValueByPath(.object(fromObject), ["outputMimeType"])
    if case .null = fromOutputMimeType {} else {
        try setValueByPath(&parentObject, ["parameters", "outputOptions", "mimeType"], fromOutputMimeType)
    }

    let fromOutputCompressionQuality = getValueByPath(.object(fromObject), ["outputCompressionQuality"])
    if case .null = fromOutputCompressionQuality {} else {
        try setValueByPath(&parentObject, ["parameters", "outputOptions", "compressionQuality"], fromOutputCompressionQuality)
    }

    let fromEnhanceInputImage = getValueByPath(.object(fromObject), ["enhanceInputImage"])
    if case .null = fromEnhanceInputImage {} else {
        try setValueByPath(&parentObject, ["parameters", "upscaleConfig", "enhanceInputImage"], fromEnhanceInputImage)
    }

    let fromImagePreservationFactor = getValueByPath(.object(fromObject), ["imagePreservationFactor"])
    if case .null = fromImagePreservationFactor {} else {
        try setValueByPath(&parentObject, ["parameters", "upscaleConfig", "imagePreservationFactor"], fromImagePreservationFactor)
    }

    let fromLabels = getValueByPath(.object(fromObject), ["labels"])
    if case .null = fromLabels {} else {
        try setValueByPath(&parentObject, ["labels"], fromLabels)
    }

    let fromNumberOfImages = getValueByPath(.object(fromObject), ["numberOfImages"])
    if case .null = fromNumberOfImages {} else {
        try setValueByPath(&parentObject, ["parameters", "sampleCount"], fromNumberOfImages)
    }

    let fromMode = getValueByPath(.object(fromObject), ["mode"])
    if case .null = fromMode {} else {
        try setValueByPath(&parentObject, ["parameters", "mode"], fromMode)
    }

    return toObject
}

// MARK: - upscaleImageAPIParametersInternalToVertex

public func upscaleImageAPIParametersInternalToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        try setValueByPath(&toObject, ["_url", "model"], .string(try tModel(apiClient: apiClient, model: fromModel)))
    }

    let fromImage = getValueByPath(.object(fromObject), ["image"])
    if case .object(let imgObj) = fromImage {
        var _dummyParent42: [String: JSONValue] = [:]
        let converted = try imageToVertex(apiClient: apiClient, fromObject: imgObj, parentObject: &_dummyParent42)
        try setValueByPath(&toObject, ["instances[0]", "image"], .object(converted))
    }

    let fromUpscaleFactor = getValueByPath(.object(fromObject), ["upscaleFactor"])
    if case .null = fromUpscaleFactor {} else {
        try setValueByPath(&toObject, ["parameters", "upscaleConfig", "upscaleFactor"], fromUpscaleFactor)
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let cfgObj) = fromConfig {
        _ = try upscaleImageAPIConfigInternalToVertex(apiClient: apiClient, fromObject: cfgObj, parentObject: &toObject)
    }

    return toObject
}

// MARK: - upscaleImageResponseFromVertex

public func upscaleImageResponseFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    let fromGeneratedImages = getValueByPath(.object(fromObject), ["predictions"])
    if case .null = fromGeneratedImages {} else {
        if case .array(let arr) = fromGeneratedImages {
            var transformed: [JSONValue] = []
            for item in arr {
                if case .object(let itemObj) = item {
                    var _dummyParent43: [String: JSONValue] = [:]
                    let converted = try generatedImageFromVertex(apiClient: apiClient, fromObject: itemObj, parentObject: &_dummyParent43)
                    transformed.append(.object(converted))
                } else {
                    transformed.append(item)
                }
            }
            try setValueByPath(&toObject, ["generatedImages"], .array(transformed))
        } else {
            try setValueByPath(&toObject, ["generatedImages"], fromGeneratedImages)
        }
    }

    return toObject
}

// MARK: - videoGenerationMaskToVertex

public func videoGenerationMaskToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromImage = getValueByPath(.object(fromObject), ["image"])
    if case .object(let imgObj) = fromImage {
        var _dummyParent44: [String: JSONValue] = [:]
        let converted = try imageToVertex(apiClient: apiClient, fromObject: imgObj, parentObject: &_dummyParent44)
        try setValueByPath(&toObject, ["_self"], .object(converted))
    }

    let fromMaskMode = getValueByPath(.object(fromObject), ["maskMode"])
    if case .null = fromMaskMode {} else {
        try setValueByPath(&toObject, ["maskMode"], fromMaskMode)
    }

    return toObject
}

// MARK: - videoGenerationReferenceImageToMldev

public func videoGenerationReferenceImageToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromImage = getValueByPath(.object(fromObject), ["image"])
    if case .object(let imgObj) = fromImage {
        var _dummyParent45: [String: JSONValue] = [:]
        let converted = try imageToMldev(apiClient: apiClient, fromObject: imgObj, parentObject: &_dummyParent45)
        try setValueByPath(&toObject, ["image"], .object(converted))
    }

    let fromReferenceType = getValueByPath(.object(fromObject), ["referenceType"])
    if case .null = fromReferenceType {} else {
        try setValueByPath(&toObject, ["referenceType"], fromReferenceType)
    }

    return toObject
}

// MARK: - videoGenerationReferenceImageToVertex

public func videoGenerationReferenceImageToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromImage = getValueByPath(.object(fromObject), ["image"])
    if case .object(let imgObj) = fromImage {
        var _dummyParent46: [String: JSONValue] = [:]
        let converted = try imageToVertex(apiClient: apiClient, fromObject: imgObj, parentObject: &_dummyParent46)
        try setValueByPath(&toObject, ["image"], .object(converted))
    }

    let fromReferenceType = getValueByPath(.object(fromObject), ["referenceType"])
    if case .null = fromReferenceType {} else {
        try setValueByPath(&toObject, ["referenceType"], fromReferenceType)
    }

    return toObject
}

// MARK: - videoToMldev

public func videoToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromUri = getValueByPath(.object(fromObject), ["uri"])
    if case .null = fromUri {} else {
        try setValueByPath(&toObject, ["uri"], fromUri)
    }

    let fromVideoBytes = getValueByPath(.object(fromObject), ["videoBytes"])
    if case .null = fromVideoBytes {} else {
        try setValueByPath(&toObject, ["encodedVideo"], .string(try tBytes(fromVideoBytes)))
    }

    let fromMimeType = getValueByPath(.object(fromObject), ["mimeType"])
    if case .null = fromMimeType {} else {
        try setValueByPath(&toObject, ["encoding"], fromMimeType)
    }

    return toObject
}

// MARK: - videoToVertex

public func videoToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]
    let rootObject: JSONValue = .object(parentObject)

    let fromUri = getValueByPath(.object(fromObject), ["uri"])
    if case .null = fromUri {} else {
        try setValueByPath(&toObject, ["gcsUri"], fromUri)
    }

    let fromVideoBytes = getValueByPath(.object(fromObject), ["videoBytes"])
    if case .null = fromVideoBytes {} else {
        try setValueByPath(&toObject, ["bytesBase64Encoded"], .string(try tBytes(fromVideoBytes)))
    }

    let fromMimeType = getValueByPath(.object(fromObject), ["mimeType"])
    if case .null = fromMimeType {} else {
        try setValueByPath(&toObject, ["mimeType"], fromMimeType)
    }

    return toObject
}
