// Copyright 2025 Google LLC
// SPDX-License-Identifier: Apache-2.0

import Foundation

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.
//
// NOTE: The following converters are also defined in `_tokens_converters.ts`
// but are duplicated in other TS converter files. To avoid Swift name
// collisions inside a single module, this file relies on the canonical
// definitions in `LiveConverters.swift`:
//   audioTranscriptionConfigToMldev, authConfigToMldev, blobToMldev,
//   contentToMldev, fileDataToMldev, functionCallToMldev,
//   googleMapsToMldev, googleSearchToMldev, liveConnectConfigToMldev,
//   partToMldev, safetySettingToMldev, sessionResumptionConfigToMldev,
//   toolToMldev.

public func createAuthTokenConfigToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromExpireTime = getValueByPath(.object(fromObject), ["expireTime"])
    if case .null = fromExpireTime {} else {
        try setValueByPath(&parentObject, ["expireTime"], fromExpireTime)
    }

    let fromNewSessionExpireTime = getValueByPath(.object(fromObject), ["newSessionExpireTime"])
    if case .null = fromNewSessionExpireTime {} else {
        try setValueByPath(&parentObject, ["newSessionExpireTime"], fromNewSessionExpireTime)
    }

    let fromUses = getValueByPath(.object(fromObject), ["uses"])
    if case .null = fromUses {} else {
        try setValueByPath(&parentObject, ["uses"], fromUses)
    }

    let fromLiveConnectConstraints = getValueByPath(.object(fromObject), ["liveConnectConstraints"])
    if case .object(let lccObj) = fromLiveConnectConstraints {
        var dummy: [String: JSONValue] = [:]
        let converted = try liveConnectConstraintsToMldev(apiClient: apiClient, fromObject: lccObj, parentObject: &dummy)
        try setValueByPath(&parentObject, ["bidiGenerateContentSetup"], .object(converted))
    }

    let fromLockAdditionalFields = getValueByPath(.object(fromObject), ["lockAdditionalFields"])
    if case .null = fromLockAdditionalFields {} else {
        try setValueByPath(&parentObject, ["fieldMask"], fromLockAdditionalFields)
    }

    return toObject
}

public func createAuthTokenParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        let converted = try createAuthTokenConfigToMldev(apiClient: apiClient, fromObject: configObj, parentObject: &toObject)
        try setValueByPath(&toObject, ["config"], .object(converted))
    }

    return toObject
}

public func createAuthTokenParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    if case .null = getValueByPath(.object(fromObject), ["config"]) {} else {
        throw GenAIError.runtime(
            "config parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode."
        )
    }

    return toObject
}

public func liveConnectConstraintsToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue]
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromModel = getValueByPath(.object(fromObject), ["model"])
    if case .null = fromModel {} else {
        let modelStr = try tModel(apiClient: apiClient, model: fromModel)
        try setValueByPath(&toObject, ["setup", "model"], .string(modelStr))
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        let converted = try liveConnectConfigToMldev(apiClient: apiClient, fromObject: configObj, parentObject: &toObject)
        try setValueByPath(&toObject, ["config"], .object(converted))
    }

    return toObject
}
