// Copyright 2025 Google LLC
// SPDX-License-Identifier: Apache-2.0

import Foundation

// Code generated by the Google Gen AI SDK generator DO NOT EDIT.

// MARK: - File-private helpers

/// Returns the discriminator value at `['config', 'method']` from rootObject, defaulting to
/// "SUPERVISED_FINE_TUNING" when missing (mirrors TS `discriminatorX === undefined`).
private func tuningMethodDiscriminator(_ rootObject: [String: JSONValue]?) -> String {
    let root: JSONValue = rootObject.map { .object($0) } ?? .null
    let value = getValueByPath(root, ["config", "method"])
    if case .string(let s) = value { return s }
    return "SUPERVISED_FINE_TUNING"
}

// MARK: - Converters

public func cancelTuningJobParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        try setValueByPath(&toObject, ["_url", "name"], fromName)
    }

    return toObject
}

public func cancelTuningJobParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        try setValueByPath(&toObject, ["_url", "name"], fromName)
    }

    return toObject
}

public func cancelTuningJobResponseFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    return toObject
}

public func cancelTuningJobResponseFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    return toObject
}

public func createTuningJobConfigToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    if case .null = getValueByPath(.object(fromObject), ["validationDataset"]) {} else {
        throw GenAIError.runtime(
            "validationDataset parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    let fromTunedModelDisplayName = getValueByPath(.object(fromObject), ["tunedModelDisplayName"])
    if case .null = fromTunedModelDisplayName {} else {
        try setValueByPath(&parentObject, ["displayName"], fromTunedModelDisplayName)
    }

    if case .null = getValueByPath(.object(fromObject), ["description"]) {} else {
        throw GenAIError.runtime(
            "description parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    let fromEpochCount = getValueByPath(.object(fromObject), ["epochCount"])
    if case .null = fromEpochCount {} else {
        try setValueByPath(&parentObject, ["tuningTask", "hyperparameters", "epochCount"], fromEpochCount)
    }

    let fromLearningRateMultiplier = getValueByPath(.object(fromObject), ["learningRateMultiplier"])
    if case .null = fromLearningRateMultiplier {} else {
        try setValueByPath(&toObject, ["tuningTask", "hyperparameters", "learningRateMultiplier"], fromLearningRateMultiplier)
    }

    if case .null = getValueByPath(.object(fromObject), ["exportLastCheckpointOnly"]) {} else {
        throw GenAIError.runtime(
            "exportLastCheckpointOnly parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["preTunedModelCheckpointId"]) {} else {
        throw GenAIError.runtime(
            "preTunedModelCheckpointId parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["adapterSize"]) {} else {
        throw GenAIError.runtime(
            "adapterSize parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["tuningMode"]) {} else {
        throw GenAIError.runtime(
            "tuningMode parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["customBaseModel"]) {} else {
        throw GenAIError.runtime(
            "customBaseModel parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    let fromBatchSize = getValueByPath(.object(fromObject), ["batchSize"])
    if case .null = fromBatchSize {} else {
        try setValueByPath(&parentObject, ["tuningTask", "hyperparameters", "batchSize"], fromBatchSize)
    }

    let fromLearningRate = getValueByPath(.object(fromObject), ["learningRate"])
    if case .null = fromLearningRate {} else {
        try setValueByPath(&parentObject, ["tuningTask", "hyperparameters", "learningRate"], fromLearningRate)
    }

    if case .null = getValueByPath(.object(fromObject), ["labels"]) {} else {
        throw GenAIError.runtime(
            "labels parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["beta"]) {} else {
        throw GenAIError.runtime(
            "beta parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["baseTeacherModel"]) {} else {
        throw GenAIError.runtime(
            "baseTeacherModel parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["tunedTeacherModelSource"]) {} else {
        throw GenAIError.runtime(
            "tunedTeacherModelSource parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["sftLossWeightMultiplier"]) {} else {
        throw GenAIError.runtime(
            "sftLossWeightMultiplier parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["outputUri"]) {} else {
        throw GenAIError.runtime(
            "outputUri parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["encryptionSpec"]) {} else {
        throw GenAIError.runtime(
            "encryptionSpec parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    return toObject
}

public func createTuningJobConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let discriminatorValidationDataset = tuningMethodDiscriminator(rootObject)
    if discriminatorValidationDataset == "SUPERVISED_FINE_TUNING" {
        let fromValidationDataset = getValueByPath(.object(fromObject), ["validationDataset"])
        if case .object(let vdObj) = fromValidationDataset {
            var dummy: [String: JSONValue] = [:]
            let converted = try tuningValidationDatasetToVertex(apiClient: apiClient, fromObject: vdObj, parentObject: &dummy, rootObject: rootObject)
            try setValueByPath(&parentObject, ["supervisedTuningSpec"], .object(converted))
        }
    } else if discriminatorValidationDataset == "PREFERENCE_TUNING" {
        let fromValidationDataset = getValueByPath(.object(fromObject), ["validationDataset"])
        if case .object(let vdObj) = fromValidationDataset {
            var dummy: [String: JSONValue] = [:]
            let converted = try tuningValidationDatasetToVertex(apiClient: apiClient, fromObject: vdObj, parentObject: &dummy, rootObject: rootObject)
            try setValueByPath(&parentObject, ["preferenceOptimizationSpec"], .object(converted))
        }
    } else if discriminatorValidationDataset == "DISTILLATION" {
        let fromValidationDataset = getValueByPath(.object(fromObject), ["validationDataset"])
        if case .object(let vdObj) = fromValidationDataset {
            var dummy: [String: JSONValue] = [:]
            let converted = try tuningValidationDatasetToVertex(apiClient: apiClient, fromObject: vdObj, parentObject: &dummy, rootObject: rootObject)
            try setValueByPath(&parentObject, ["distillationSpec"], .object(converted))
        }
    }

    let fromTunedModelDisplayName = getValueByPath(.object(fromObject), ["tunedModelDisplayName"])
    if case .null = fromTunedModelDisplayName {} else {
        try setValueByPath(&parentObject, ["tunedModelDisplayName"], fromTunedModelDisplayName)
    }

    let fromDescription = getValueByPath(.object(fromObject), ["description"])
    if case .null = fromDescription {} else {
        try setValueByPath(&parentObject, ["description"], fromDescription)
    }

    let discriminatorEpochCount = tuningMethodDiscriminator(rootObject)
    if discriminatorEpochCount == "SUPERVISED_FINE_TUNING" {
        let fromEpochCount = getValueByPath(.object(fromObject), ["epochCount"])
        if case .null = fromEpochCount {} else {
            try setValueByPath(&parentObject, ["supervisedTuningSpec", "hyperParameters", "epochCount"], fromEpochCount)
        }
    } else if discriminatorEpochCount == "PREFERENCE_TUNING" {
        let fromEpochCount = getValueByPath(.object(fromObject), ["epochCount"])
        if case .null = fromEpochCount {} else {
            try setValueByPath(&parentObject, ["preferenceOptimizationSpec", "hyperParameters", "epochCount"], fromEpochCount)
        }
    } else if discriminatorEpochCount == "DISTILLATION" {
        let fromEpochCount = getValueByPath(.object(fromObject), ["epochCount"])
        if case .null = fromEpochCount {} else {
            try setValueByPath(&parentObject, ["distillationSpec", "hyperParameters", "epochCount"], fromEpochCount)
        }
    }

    let discriminatorLearningRateMultiplier = tuningMethodDiscriminator(rootObject)
    if discriminatorLearningRateMultiplier == "SUPERVISED_FINE_TUNING" {
        let fromLearningRateMultiplier = getValueByPath(.object(fromObject), ["learningRateMultiplier"])
        if case .null = fromLearningRateMultiplier {} else {
            try setValueByPath(&parentObject, ["supervisedTuningSpec", "hyperParameters", "learningRateMultiplier"], fromLearningRateMultiplier)
        }
    } else if discriminatorLearningRateMultiplier == "PREFERENCE_TUNING" {
        let fromLearningRateMultiplier = getValueByPath(.object(fromObject), ["learningRateMultiplier"])
        if case .null = fromLearningRateMultiplier {} else {
            try setValueByPath(&parentObject, ["preferenceOptimizationSpec", "hyperParameters", "learningRateMultiplier"], fromLearningRateMultiplier)
        }
    } else if discriminatorLearningRateMultiplier == "DISTILLATION" {
        let fromLearningRateMultiplier = getValueByPath(.object(fromObject), ["learningRateMultiplier"])
        if case .null = fromLearningRateMultiplier {} else {
            try setValueByPath(&parentObject, ["distillationSpec", "hyperParameters", "learningRateMultiplier"], fromLearningRateMultiplier)
        }
    }

    let discriminatorExportLastCheckpointOnly = tuningMethodDiscriminator(rootObject)
    if discriminatorExportLastCheckpointOnly == "SUPERVISED_FINE_TUNING" {
        let fromExportLastCheckpointOnly = getValueByPath(.object(fromObject), ["exportLastCheckpointOnly"])
        if case .null = fromExportLastCheckpointOnly {} else {
            try setValueByPath(&parentObject, ["supervisedTuningSpec", "exportLastCheckpointOnly"], fromExportLastCheckpointOnly)
        }
    } else if discriminatorExportLastCheckpointOnly == "PREFERENCE_TUNING" {
        let fromExportLastCheckpointOnly = getValueByPath(.object(fromObject), ["exportLastCheckpointOnly"])
        if case .null = fromExportLastCheckpointOnly {} else {
            try setValueByPath(&parentObject, ["preferenceOptimizationSpec", "exportLastCheckpointOnly"], fromExportLastCheckpointOnly)
        }
    } else if discriminatorExportLastCheckpointOnly == "DISTILLATION" {
        let fromExportLastCheckpointOnly = getValueByPath(.object(fromObject), ["exportLastCheckpointOnly"])
        if case .null = fromExportLastCheckpointOnly {} else {
            try setValueByPath(&parentObject, ["distillationSpec", "exportLastCheckpointOnly"], fromExportLastCheckpointOnly)
        }
    }

    let discriminatorAdapterSize = tuningMethodDiscriminator(rootObject)
    if discriminatorAdapterSize == "SUPERVISED_FINE_TUNING" {
        let fromAdapterSize = getValueByPath(.object(fromObject), ["adapterSize"])
        if case .null = fromAdapterSize {} else {
            try setValueByPath(&parentObject, ["supervisedTuningSpec", "hyperParameters", "adapterSize"], fromAdapterSize)
        }
    } else if discriminatorAdapterSize == "PREFERENCE_TUNING" {
        let fromAdapterSize = getValueByPath(.object(fromObject), ["adapterSize"])
        if case .null = fromAdapterSize {} else {
            try setValueByPath(&parentObject, ["preferenceOptimizationSpec", "hyperParameters", "adapterSize"], fromAdapterSize)
        }
    } else if discriminatorAdapterSize == "DISTILLATION" {
        let fromAdapterSize = getValueByPath(.object(fromObject), ["adapterSize"])
        if case .null = fromAdapterSize {} else {
            try setValueByPath(&parentObject, ["distillationSpec", "hyperParameters", "adapterSize"], fromAdapterSize)
        }
    }

    let discriminatorTuningMode = tuningMethodDiscriminator(rootObject)
    if discriminatorTuningMode == "SUPERVISED_FINE_TUNING" {
        let fromTuningMode = getValueByPath(.object(fromObject), ["tuningMode"])
        if case .null = fromTuningMode {} else {
            try setValueByPath(&parentObject, ["supervisedTuningSpec", "tuningMode"], fromTuningMode)
        }
    } else if discriminatorTuningMode == "DISTILLATION" {
        let fromTuningMode = getValueByPath(.object(fromObject), ["tuningMode"])
        if case .null = fromTuningMode {} else {
            try setValueByPath(&parentObject, ["distillationSpec", "tuningMode"], fromTuningMode)
        }
    }

    let fromCustomBaseModel = getValueByPath(.object(fromObject), ["customBaseModel"])
    if case .null = fromCustomBaseModel {} else {
        try setValueByPath(&parentObject, ["customBaseModel"], fromCustomBaseModel)
    }

    let discriminatorBatchSize = tuningMethodDiscriminator(rootObject)
    if discriminatorBatchSize == "SUPERVISED_FINE_TUNING" {
        let fromBatchSize = getValueByPath(.object(fromObject), ["batchSize"])
        if case .null = fromBatchSize {} else {
            try setValueByPath(&parentObject, ["supervisedTuningSpec", "hyperParameters", "batchSize"], fromBatchSize)
        }
    } else if discriminatorBatchSize == "DISTILLATION" {
        let fromBatchSize = getValueByPath(.object(fromObject), ["batchSize"])
        if case .null = fromBatchSize {} else {
            try setValueByPath(&parentObject, ["distillationSpec", "hyperParameters", "batchSize"], fromBatchSize)
        }
    }

    let discriminatorLearningRate = tuningMethodDiscriminator(rootObject)
    if discriminatorLearningRate == "SUPERVISED_FINE_TUNING" {
        let fromLearningRate = getValueByPath(.object(fromObject), ["learningRate"])
        if case .null = fromLearningRate {} else {
            try setValueByPath(&parentObject, ["supervisedTuningSpec", "hyperParameters", "learningRate"], fromLearningRate)
        }
    } else if discriminatorLearningRate == "DISTILLATION" {
        let fromLearningRate = getValueByPath(.object(fromObject), ["learningRate"])
        if case .null = fromLearningRate {} else {
            try setValueByPath(&parentObject, ["distillationSpec", "hyperParameters", "learningRate"], fromLearningRate)
        }
    }

    let fromLabels = getValueByPath(.object(fromObject), ["labels"])
    if case .null = fromLabels {} else {
        try setValueByPath(&parentObject, ["labels"], fromLabels)
    }

    let fromBeta = getValueByPath(.object(fromObject), ["beta"])
    if case .null = fromBeta {} else {
        try setValueByPath(&parentObject, ["preferenceOptimizationSpec", "hyperParameters", "beta"], fromBeta)
    }

    let fromBaseTeacherModel = getValueByPath(.object(fromObject), ["baseTeacherModel"])
    if case .null = fromBaseTeacherModel {} else {
        try setValueByPath(&parentObject, ["distillationSpec", "baseTeacherModel"], fromBaseTeacherModel)
    }

    let fromTunedTeacherModelSource = getValueByPath(.object(fromObject), ["tunedTeacherModelSource"])
    if case .null = fromTunedTeacherModelSource {} else {
        try setValueByPath(&parentObject, ["distillationSpec", "tunedTeacherModelSource"], fromTunedTeacherModelSource)
    }

    let fromSftLossWeightMultiplier = getValueByPath(.object(fromObject), ["sftLossWeightMultiplier"])
    if case .null = fromSftLossWeightMultiplier {} else {
        try setValueByPath(&parentObject, ["distillationSpec", "hyperParameters", "sftLossWeightMultiplier"], fromSftLossWeightMultiplier)
    }

    let fromOutputUri = getValueByPath(.object(fromObject), ["outputUri"])
    if case .null = fromOutputUri {} else {
        try setValueByPath(&parentObject, ["outputUri"], fromOutputUri)
    }

    let fromEncryptionSpec = getValueByPath(.object(fromObject), ["encryptionSpec"])
    if case .null = fromEncryptionSpec {} else {
        try setValueByPath(&parentObject, ["encryptionSpec"], fromEncryptionSpec)
    }

    return toObject
}

public func createTuningJobParametersPrivateToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromBaseModel = getValueByPath(.object(fromObject), ["baseModel"])
    if case .null = fromBaseModel {} else {
        try setValueByPath(&toObject, ["baseModel"], fromBaseModel)
    }

    let fromPreTunedModel = getValueByPath(.object(fromObject), ["preTunedModel"])
    if case .null = fromPreTunedModel {} else {
        try setValueByPath(&toObject, ["preTunedModel"], fromPreTunedModel)
    }

    let fromTrainingDataset = getValueByPath(.object(fromObject), ["trainingDataset"])
    if case .object(let tdObj) = fromTrainingDataset {
        var dummy: [String: JSONValue] = [:]
        _ = try tuningDatasetToMldev(apiClient: apiClient, fromObject: tdObj, parentObject: &dummy, rootObject: rootObject)
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try createTuningJobConfigToMldev(apiClient: apiClient, fromObject: configObj, parentObject: &toObject, rootObject: rootObject)
    }

    return toObject
}

public func createTuningJobParametersPrivateToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromBaseModel = getValueByPath(.object(fromObject), ["baseModel"])
    if case .null = fromBaseModel {} else {
        try setValueByPath(&toObject, ["baseModel"], fromBaseModel)
    }

    let fromPreTunedModel = getValueByPath(.object(fromObject), ["preTunedModel"])
    if case .null = fromPreTunedModel {} else {
        try setValueByPath(&toObject, ["preTunedModel"], fromPreTunedModel)
    }

    let fromTrainingDataset = getValueByPath(.object(fromObject), ["trainingDataset"])
    if case .object(let tdObj) = fromTrainingDataset {
        _ = try tuningDatasetToVertex(apiClient: apiClient, fromObject: tdObj, parentObject: &toObject, rootObject: rootObject)
    }

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try createTuningJobConfigToVertex(apiClient: apiClient, fromObject: configObj, parentObject: &toObject, rootObject: rootObject)
    }

    return toObject
}

public func getTuningJobParametersToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        try setValueByPath(&toObject, ["_url", "name"], fromName)
    }

    return toObject
}

public func getTuningJobParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        try setValueByPath(&toObject, ["_url", "name"], fromName)
    }

    return toObject
}

public func listTuningJobsConfigToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromPageSize = getValueByPath(.object(fromObject), ["pageSize"])
    if case .null = fromPageSize {} else {
        try setValueByPath(&parentObject, ["_query", "pageSize"], fromPageSize)
    }

    let fromPageToken = getValueByPath(.object(fromObject), ["pageToken"])
    if case .null = fromPageToken {} else {
        try setValueByPath(&parentObject, ["_query", "pageToken"], fromPageToken)
    }

    let fromFilter = getValueByPath(.object(fromObject), ["filter"])
    if case .null = fromFilter {} else {
        try setValueByPath(&parentObject, ["_query", "filter"], fromFilter)
    }

    return toObject
}

public func listTuningJobsParametersToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromConfig = getValueByPath(.object(fromObject), ["config"])
    if case .object(let configObj) = fromConfig {
        _ = try listTuningJobsConfigToVertex(apiClient: apiClient, fromObject: configObj, parentObject: &toObject, rootObject: rootObject)
    }

    return toObject
}

public func listTuningJobsResponseFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    let fromNextPageToken = getValueByPath(.object(fromObject), ["nextPageToken"])
    if case .null = fromNextPageToken {} else {
        try setValueByPath(&toObject, ["nextPageToken"], fromNextPageToken)
    }

    let fromTuningJobs = getValueByPath(.object(fromObject), ["tuningJobs"])
    if case .null = fromTuningJobs {} else {
        var transformed: JSONValue = fromTuningJobs
        if case .array(let arr) = fromTuningJobs {
            var mapped: [JSONValue] = []
            for item in arr {
                if case .object(let itemObj) = item {
                    var dummy: [String: JSONValue] = [:]
                    let result = try tuningJobFromVertex(apiClient: apiClient, fromObject: itemObj, parentObject: &dummy, rootObject: rootObject)
                    mapped.append(.object(result))
                } else {
                    mapped.append(item)
                }
            }
            transformed = .array(mapped)
        }
        try setValueByPath(&toObject, ["tuningJobs"], transformed)
    }

    return toObject
}

public func tunedModelFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromModel = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromModel {} else {
        try setValueByPath(&toObject, ["model"], fromModel)
    }

    let fromEndpoint = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromEndpoint {} else {
        try setValueByPath(&toObject, ["endpoint"], fromEndpoint)
    }

    return toObject
}

public func tuningDatasetToMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    if case .null = getValueByPath(.object(fromObject), ["gcsUri"]) {} else {
        throw GenAIError.runtime(
            "gcsUri parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    if case .null = getValueByPath(.object(fromObject), ["vertexDatasetResource"]) {} else {
        throw GenAIError.runtime(
            "vertexDatasetResource parameter is only supported in Gemini Enterprise Agent Platform mode, not in Gemini Developer API mode."
        )
    }

    let fromExamples = getValueByPath(.object(fromObject), ["examples"])
    if case .null = fromExamples {} else {
        try setValueByPath(&toObject, ["examples", "examples"], fromExamples)
    }

    return toObject
}

public func tuningDatasetToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let discriminatorGcsUri = tuningMethodDiscriminator(rootObject)
    if discriminatorGcsUri == "SUPERVISED_FINE_TUNING" {
        let fromGcsUri = getValueByPath(.object(fromObject), ["gcsUri"])
        if case .null = fromGcsUri {} else {
            try setValueByPath(&parentObject, ["supervisedTuningSpec", "trainingDatasetUri"], fromGcsUri)
        }
    } else if discriminatorGcsUri == "PREFERENCE_TUNING" {
        let fromGcsUri = getValueByPath(.object(fromObject), ["gcsUri"])
        if case .null = fromGcsUri {} else {
            try setValueByPath(&parentObject, ["preferenceOptimizationSpec", "trainingDatasetUri"], fromGcsUri)
        }
    } else if discriminatorGcsUri == "DISTILLATION" {
        let fromGcsUri = getValueByPath(.object(fromObject), ["gcsUri"])
        if case .null = fromGcsUri {} else {
            try setValueByPath(&parentObject, ["distillationSpec", "promptDatasetUri"], fromGcsUri)
        }
    }

    let discriminatorVertexDatasetResource = tuningMethodDiscriminator(rootObject)
    if discriminatorVertexDatasetResource == "SUPERVISED_FINE_TUNING" {
        let fromVertexDatasetResource = getValueByPath(.object(fromObject), ["vertexDatasetResource"])
        if case .null = fromVertexDatasetResource {} else {
            try setValueByPath(&parentObject, ["supervisedTuningSpec", "trainingDatasetUri"], fromVertexDatasetResource)
        }
    } else if discriminatorVertexDatasetResource == "PREFERENCE_TUNING" {
        let fromVertexDatasetResource = getValueByPath(.object(fromObject), ["vertexDatasetResource"])
        if case .null = fromVertexDatasetResource {} else {
            try setValueByPath(&parentObject, ["preferenceOptimizationSpec", "trainingDatasetUri"], fromVertexDatasetResource)
        }
    } else if discriminatorVertexDatasetResource == "DISTILLATION" {
        let fromVertexDatasetResource = getValueByPath(.object(fromObject), ["vertexDatasetResource"])
        if case .null = fromVertexDatasetResource {} else {
            try setValueByPath(&parentObject, ["distillationSpec", "promptDatasetUri"], fromVertexDatasetResource)
        }
    }

    if case .null = getValueByPath(.object(fromObject), ["examples"]) {} else {
        throw GenAIError.runtime(
            "examples parameter is only supported in Gemini Developer API mode, not in Gemini Enterprise Agent Platform mode."
        )
    }

    return toObject
}

public func tuningJobFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        try setValueByPath(&toObject, ["name"], fromName)
    }

    let fromState = getValueByPath(.object(fromObject), ["state"])
    if case .null = fromState {} else {
        let statusStr = tTuningJobStatus(fromState)
        try setValueByPath(&toObject, ["state"], .string(statusStr))
    }

    let fromCreateTime = getValueByPath(.object(fromObject), ["createTime"])
    if case .null = fromCreateTime {} else {
        try setValueByPath(&toObject, ["createTime"], fromCreateTime)
    }

    let fromStartTime = getValueByPath(.object(fromObject), ["tuningTask", "startTime"])
    if case .null = fromStartTime {} else {
        try setValueByPath(&toObject, ["startTime"], fromStartTime)
    }

    let fromEndTime = getValueByPath(.object(fromObject), ["tuningTask", "completeTime"])
    if case .null = fromEndTime {} else {
        try setValueByPath(&toObject, ["endTime"], fromEndTime)
    }

    let fromUpdateTime = getValueByPath(.object(fromObject), ["updateTime"])
    if case .null = fromUpdateTime {} else {
        try setValueByPath(&toObject, ["updateTime"], fromUpdateTime)
    }

    let fromDescription = getValueByPath(.object(fromObject), ["description"])
    if case .null = fromDescription {} else {
        try setValueByPath(&toObject, ["description"], fromDescription)
    }

    let fromBaseModel = getValueByPath(.object(fromObject), ["baseModel"])
    if case .null = fromBaseModel {} else {
        try setValueByPath(&toObject, ["baseModel"], fromBaseModel)
    }

    let fromTunedModel = getValueByPath(.object(fromObject), ["_self"])
    if case .null = fromTunedModel {} else {
        let tmObj: [String: JSONValue]
        if case .object(let o) = fromTunedModel { tmObj = o } else { tmObj = [:] }
        var dummy: [String: JSONValue] = [:]
        let converted = try tunedModelFromMldev(apiClient: apiClient, fromObject: tmObj, parentObject: &dummy, rootObject: rootObject)
        try setValueByPath(&toObject, ["tunedModel"], .object(converted))
    }

    return toObject
}

public func tuningJobFromVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        try setValueByPath(&toObject, ["name"], fromName)
    }

    let fromState = getValueByPath(.object(fromObject), ["state"])
    if case .null = fromState {} else {
        let statusStr = tTuningJobStatus(fromState)
        try setValueByPath(&toObject, ["state"], .string(statusStr))
    }

    let fromCreateTime = getValueByPath(.object(fromObject), ["createTime"])
    if case .null = fromCreateTime {} else {
        try setValueByPath(&toObject, ["createTime"], fromCreateTime)
    }

    let fromStartTime = getValueByPath(.object(fromObject), ["startTime"])
    if case .null = fromStartTime {} else {
        try setValueByPath(&toObject, ["startTime"], fromStartTime)
    }

    let fromEndTime = getValueByPath(.object(fromObject), ["endTime"])
    if case .null = fromEndTime {} else {
        try setValueByPath(&toObject, ["endTime"], fromEndTime)
    }

    let fromUpdateTime = getValueByPath(.object(fromObject), ["updateTime"])
    if case .null = fromUpdateTime {} else {
        try setValueByPath(&toObject, ["updateTime"], fromUpdateTime)
    }

    let fromError = getValueByPath(.object(fromObject), ["error"])
    if case .null = fromError {} else {
        try setValueByPath(&toObject, ["error"], fromError)
    }

    let fromDescription = getValueByPath(.object(fromObject), ["description"])
    if case .null = fromDescription {} else {
        try setValueByPath(&toObject, ["description"], fromDescription)
    }

    let fromBaseModel = getValueByPath(.object(fromObject), ["baseModel"])
    if case .null = fromBaseModel {} else {
        try setValueByPath(&toObject, ["baseModel"], fromBaseModel)
    }

    let fromTunedModel = getValueByPath(.object(fromObject), ["tunedModel"])
    if case .null = fromTunedModel {} else {
        try setValueByPath(&toObject, ["tunedModel"], fromTunedModel)
    }

    let fromPreTunedModel = getValueByPath(.object(fromObject), ["preTunedModel"])
    if case .null = fromPreTunedModel {} else {
        try setValueByPath(&toObject, ["preTunedModel"], fromPreTunedModel)
    }

    let fromSupervisedTuningSpec = getValueByPath(.object(fromObject), ["supervisedTuningSpec"])
    if case .null = fromSupervisedTuningSpec {} else {
        try setValueByPath(&toObject, ["supervisedTuningSpec"], fromSupervisedTuningSpec)
    }

    let fromPreferenceOptimizationSpec = getValueByPath(.object(fromObject), ["preferenceOptimizationSpec"])
    if case .null = fromPreferenceOptimizationSpec {} else {
        try setValueByPath(&toObject, ["preferenceOptimizationSpec"], fromPreferenceOptimizationSpec)
    }

    let fromDistillationSpec = getValueByPath(.object(fromObject), ["distillationSpec"])
    if case .null = fromDistillationSpec {} else {
        try setValueByPath(&toObject, ["distillationSpec"], fromDistillationSpec)
    }

    let fromTuningDataStats = getValueByPath(.object(fromObject), ["tuningDataStats"])
    if case .null = fromTuningDataStats {} else {
        try setValueByPath(&toObject, ["tuningDataStats"], fromTuningDataStats)
    }

    let fromEncryptionSpec = getValueByPath(.object(fromObject), ["encryptionSpec"])
    if case .null = fromEncryptionSpec {} else {
        try setValueByPath(&toObject, ["encryptionSpec"], fromEncryptionSpec)
    }

    let fromPartnerModelTuningSpec = getValueByPath(.object(fromObject), ["partnerModelTuningSpec"])
    if case .null = fromPartnerModelTuningSpec {} else {
        try setValueByPath(&toObject, ["partnerModelTuningSpec"], fromPartnerModelTuningSpec)
    }

    let fromCustomBaseModel = getValueByPath(.object(fromObject), ["customBaseModel"])
    if case .null = fromCustomBaseModel {} else {
        try setValueByPath(&toObject, ["customBaseModel"], fromCustomBaseModel)
    }

    let fromEvaluateDatasetRuns = getValueByPath(.object(fromObject), ["evaluateDatasetRuns"])
    if case .null = fromEvaluateDatasetRuns {} else {
        try setValueByPath(&toObject, ["evaluateDatasetRuns"], fromEvaluateDatasetRuns)
    }

    let fromExperiment = getValueByPath(.object(fromObject), ["experiment"])
    if case .null = fromExperiment {} else {
        try setValueByPath(&toObject, ["experiment"], fromExperiment)
    }

    let fromFullFineTuningSpec = getValueByPath(.object(fromObject), ["fullFineTuningSpec"])
    if case .null = fromFullFineTuningSpec {} else {
        try setValueByPath(&toObject, ["fullFineTuningSpec"], fromFullFineTuningSpec)
    }

    let fromLabels = getValueByPath(.object(fromObject), ["labels"])
    if case .null = fromLabels {} else {
        try setValueByPath(&toObject, ["labels"], fromLabels)
    }

    let fromOutputUri = getValueByPath(.object(fromObject), ["outputUri"])
    if case .null = fromOutputUri {} else {
        try setValueByPath(&toObject, ["outputUri"], fromOutputUri)
    }

    let fromPipelineJob = getValueByPath(.object(fromObject), ["pipelineJob"])
    if case .null = fromPipelineJob {} else {
        try setValueByPath(&toObject, ["pipelineJob"], fromPipelineJob)
    }

    let fromServiceAccount = getValueByPath(.object(fromObject), ["serviceAccount"])
    if case .null = fromServiceAccount {} else {
        try setValueByPath(&toObject, ["serviceAccount"], fromServiceAccount)
    }

    let fromTunedModelDisplayName = getValueByPath(.object(fromObject), ["tunedModelDisplayName"])
    if case .null = fromTunedModelDisplayName {} else {
        try setValueByPath(&toObject, ["tunedModelDisplayName"], fromTunedModelDisplayName)
    }

    let fromTuningJobState = getValueByPath(.object(fromObject), ["tuningJobState"])
    if case .null = fromTuningJobState {} else {
        try setValueByPath(&toObject, ["tuningJobState"], fromTuningJobState)
    }

    let fromVeoTuningSpec = getValueByPath(.object(fromObject), ["veoTuningSpec"])
    if case .null = fromVeoTuningSpec {} else {
        try setValueByPath(&toObject, ["veoTuningSpec"], fromVeoTuningSpec)
    }

    let fromDistillationSamplingSpec = getValueByPath(.object(fromObject), ["distillationSamplingSpec"])
    if case .null = fromDistillationSamplingSpec {} else {
        try setValueByPath(&toObject, ["distillationSamplingSpec"], fromDistillationSamplingSpec)
    }

    let fromTuningJobMetadata = getValueByPath(.object(fromObject), ["tuningJobMetadata"])
    if case .null = fromTuningJobMetadata {} else {
        try setValueByPath(&toObject, ["tuningJobMetadata"], fromTuningJobMetadata)
    }

    return toObject
}

public func tuningOperationFromMldev(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromSdkHttpResponse = getValueByPath(.object(fromObject), ["sdkHttpResponse"])
    if case .null = fromSdkHttpResponse {} else {
        try setValueByPath(&toObject, ["sdkHttpResponse"], fromSdkHttpResponse)
    }

    let fromName = getValueByPath(.object(fromObject), ["name"])
    if case .null = fromName {} else {
        try setValueByPath(&toObject, ["name"], fromName)
    }

    let fromMetadata = getValueByPath(.object(fromObject), ["metadata"])
    if case .null = fromMetadata {} else {
        try setValueByPath(&toObject, ["metadata"], fromMetadata)
    }

    let fromDone = getValueByPath(.object(fromObject), ["done"])
    if case .null = fromDone {} else {
        try setValueByPath(&toObject, ["done"], fromDone)
    }

    let fromError = getValueByPath(.object(fromObject), ["error"])
    if case .null = fromError {} else {
        try setValueByPath(&toObject, ["error"], fromError)
    }

    return toObject
}

public func tuningValidationDatasetToVertex(
    apiClient: ApiClient,
    fromObject: [String: JSONValue],
    parentObject: inout [String: JSONValue],
    rootObject: [String: JSONValue]? = nil
) throws -> [String: JSONValue] {
    var toObject: [String: JSONValue] = [:]

    let fromGcsUri = getValueByPath(.object(fromObject), ["gcsUri"])
    if case .null = fromGcsUri {} else {
        try setValueByPath(&toObject, ["validationDatasetUri"], fromGcsUri)
    }

    let fromVertexDatasetResource = getValueByPath(.object(fromObject), ["vertexDatasetResource"])
    if case .null = fromVertexDatasetResource {} else {
        try setValueByPath(&toObject, ["validationDatasetUri"], fromVertexDatasetResource)
    }

    return toObject
}
